package de.itemis.mps.editor.diagram.runtime.model;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell_Collection;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;

public interface IDiagramCell extends EditorCell_Collection {
  DiagramModel getDiagramModel();
  void setFixedSize(double width, double height);
  void clearFixedSize();
  @Nullable
  Tuples._2<Double, Double> getFixedSize();
}
