package de.slisson.mps.editor.multiline.demolang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.cells.KeyMap;
import java.util.Arrays;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ConceptA_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new ConceptB_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Constant_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new RootConcept_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new SelectionTest_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new TestConcept_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<KeyMap> getDeclaredKeyMaps() {
    return Arrays.<KeyMap>asList(new km());
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x26a9201de70b4755L, 0xacd640baf7a63b3aL, 0x6f1c586ef000f6d1L), MetaIdFactory.conceptId(0x26a9201de70b4755L, 0xacd640baf7a63b3aL, 0x4f217eba04e9986aL), MetaIdFactory.conceptId(0x26a9201de70b4755L, 0xacd640baf7a63b3aL, 0x1e7f894ff124b636L), MetaIdFactory.conceptId(0x26a9201de70b4755L, 0xacd640baf7a63b3aL, 0x6f1c586ef0010120L), MetaIdFactory.conceptId(0x26a9201de70b4755L, 0xacd640baf7a63b3aL, 0x58d1fdc908f3f2d7L), MetaIdFactory.conceptId(0x26a9201de70b4755L, 0xacd640baf7a63b3aL, 0x2bd382fd31d99cd9L)).seal();
}
