package de.q60.mps.polymorphicfunctions.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class PolymorphicFunctionCall_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
    for (SNode param : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.parameterValues$q6ot))) {
      _context.getBuilder().build((SNode) param);
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink parameterValues$q6ot = MetaAdapterFactory.getContainmentLink(0xbc963c22d41949b6L, 0x8543ea411eb9d3a1L, 0x34ef63ad86efaa0eL, 0x34ef63ad86efaa8fL, "parameterValues");
  }
}
