package de.q60.mps.shadowmodels.runtime.engine;

/*Generated by MPS */

import org.modelix.model.api.IConcept;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;

public abstract class BuilderContextBase implements IBuilderContext {

  public abstract IBuilderContext createNode(IConcept concept, IBuilderContext topmost);
  public abstract void createNode(IContainmentTarget call, IBuilderContext topmost);

  @Override
  public final IBuilderContext createNode(IConcept concept) {
    return createNode(concept, this);
  }

  @Override
  public final void createNode(IContainmentTarget call) {
    createNode(call, this);
  }

  @Override
  public IBuilderContext withAdditionalIdPrefix(String prefix) {
    String existingPrefix = getParameter(BuilderContextParameter.ID_PREFIX);
    if (existingPrefix == null) {
      existingPrefix = "";
    }
    return withParameter(BuilderContextParameter.ID_PREFIX, existingPrefix + prefix);
  }

  @Override
  public <T> IBuilderContext withParameter(BuilderContextParameter<T> parameter, T value) {
    return new ContextWithParameter(this, parameter, value);
  }

  @Override
  public IBuilderContext withLabel(String label) {
    return withParameter(BuilderContextParameter.LOCAL_LABEL, label);
  }

  @Override
  public IBuilderContext forChildRole(String role) {
    return withParameter(BuilderContextParameter.ROLE, role);
  }

  @Override
  public IBuilderContext forContextValue(Object value) {
    return withParameter(BuilderContextParameter.UNDERSCORE, value);
  }

  @Override
  public <T> T getParameter(BuilderContextParameter<T> parameter) {
    return null;
  }

  @Override
  public final Object getContextValue() {
    return getParameter(BuilderContextParameter.UNDERSCORE);
  }

  @Override
  public TransformationResult.ResultElement getResultElement() {
    throw new UnsupportedOperationException("No node created yet");
  }

  protected String idWithPrefix(IBuilderContext topmost) {
    String prefix = topmost.getParameter(BuilderContextParameter.ID_PREFIX);
    String id = topmost.getParameter(BuilderContextParameter.ID);
    if (id == null) {
      return null;
    }
    if (prefix == null) {
      return id;
    }
    return prefix + id;
  }

  @Override
  public <T> T compute(_FunctionTypes._return_P1_E0<? extends T, ? super IBuilderContext> callback) {
    return callback.invoke(this);
  }

  @Override
  public void run(_FunctionTypes._void_P1_E0<? super IBuilderContext> callback) {
    callback.invoke(this);
  }
}
