package com.jetbrains.mpsext.richtext.styles.ui;

/*Generated by MPS */

import javax.swing.JButton;
import org.jetbrains.mps.openapi.model.SNodeReference;
import org.jetbrains.mps.openapi.module.SRepository;
import org.jetbrains.mps.openapi.module.ModelAccess;
import org.jetbrains.mps.openapi.language.SProperty;
import java.awt.Color;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import com.intellij.ide.IdeBundle;
import java.awt.Dimension;
import com.intellij.util.ui.JBUI;
import javax.swing.BorderFactory;
import com.intellij.ui.JBColor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import com.intellij.openapi.ui.JBPopupMenu;
import javax.swing.JMenuItem;
import java.awt.Graphics;
import java.awt.Graphics2D;
import com.intellij.ui.ColorPicker;
import java.util.Collections;
import com.intellij.ui.ColorPickerListener;
import com.jetbrains.mpsext.richtext.styles.util.RichtextColorUtil;
import java.util.Objects;
import org.jetbrains.annotations.Nullable;

/**
 * Provides a visual editor for a rich-text color property.
 * 
 * The component displays the current color as a compact preview and opens the IntelliJ color picker when activated.
 * 
 * @author Venkat Prithvi
 */
public class RichTextColorEditor extends JButton {
  private static final String CHOOSE_COLOR_MESSAGE_KEY = "dialog.title.choose.color";
  private static final String CLEAR_COLOR_TEXT = "Clear Color";

  private final SNodeReference nodeReference;
  private final SRepository repository;
  private final ModelAccess modelAccess;
  private final SProperty property;
  private final String chooseColorText;
  private Color previewColor;

  public RichTextColorEditor(@NotNull SNode node, @NotNull SProperty colorProperty, @NotNull EditorContext editorContext) {
    this.nodeReference = node.getReference();
    this.property = colorProperty;
    this.repository = editorContext.getRepository();
    this.modelAccess = repository.getModelAccess();
    this.chooseColorText = IdeBundle.message(CHOOSE_COLOR_MESSAGE_KEY);

    Dimension size = JBUI.size(16, 16);
    setPreferredSize(size);
    setMinimumSize(size);
    setMaximumSize(size);

    setToolTipText(chooseColorText);
    setFocusable(false);
    setFocusPainted(false);
    setContentAreaFilled(false);
    setOpaque(false);
    setBorderPainted(true);
    setBorder(BorderFactory.createLineBorder(new JBColor(Color.BLACK, Color.WHITE)));

    getAccessibleContext().setAccessibleName(chooseColorText);
    updatePreview(getCurrentColor());
    addActionListener((e) -> chooseColor());

    // enhance user experience by providing a simple context menu to clear the color property
    addMouseListener(new MouseAdapter() {
      @Override
      public void mousePressed(MouseEvent e) {
        if (e.isPopupTrigger()) {
          showPopupMenu(e);
        }
      }
      @Override
      public void mouseReleased(MouseEvent e) {
        if (e.isPopupTrigger()) {
          showPopupMenu(e);
        }
      }
    });
  }

  /**
   * Builds and shows the context menu for the color preview.
   * 
   * @param event the mouse event that triggered the context menu
   */
  private void showPopupMenu(MouseEvent event) {
    JBPopupMenu menu = new JBPopupMenu();
    JMenuItem clearItem = new JMenuItem(CLEAR_COLOR_TEXT);
    clearItem.setEnabled(getCurrentColor() != null);
    clearItem.addActionListener((e) -> clearColor());
    menu.add(clearItem);
    menu.show(event.getComponent(), event.getX(), event.getY());
  }

  /**
   * Clears the configured color.
   */
  private void clearColor() {
    modelAccess.executeCommand(() -> {
      SNode node = nodeReference.resolve(repository);
      if (node == null) {
        return;
      }
      node.setProperty(property, "");
    });
    updatePreview(null);
  }

  @Override
  protected void paintComponent(Graphics graphics) {
    super.paintComponent(graphics);
    Graphics2D graphics2D = (Graphics2D) graphics.create();
    try {
      if (previewColor != null) {
        graphics2D.setColor(previewColor);
        graphics2D.fillRect(0, 0, getWidth(), getHeight());
        return;
      }
      graphics2D.setColor(JBColor.namedColor("Panel.background", Color.WHITE));
      graphics2D.fillRect(0, 0, getWidth(), getHeight());
    } finally {
      graphics2D.dispose();
    }
  }

  /**
   * Opens the color picker and stores the selected color in the model.
   */
  private void chooseColor() {
    Color selectedColor = ColorPicker.showDialog(this, chooseColorText, getCurrentColor(), true, Collections.<ColorPickerListener>emptyList(), false);
    if (selectedColor == null) {
      return;
    }

    final String value = RichtextColorUtil.toModelValue(selectedColor);
    modelAccess.executeCommand(() -> {
      SNode node = nodeReference.resolve(repository);
      if (node == null) {
        return;
      }
      String currentValue = node.getProperty(property);
      if (Objects.equals(value, currentValue)) {
        return;
      }
      node.setProperty(property, value);
    });
    updatePreview(selectedColor);
  }

  /**
   * Reads and converts the current model value.
   * 
   * @return the current color or null when no color is configured
   */
  private Color getCurrentColor() {
    String value = modelAccess.computeReadAction(() -> {
      SNode node = nodeReference.resolve(repository);
      return (node == null ? null : node.getProperty(property));
    });

    return RichtextColorUtil.toAwtColor(value);
  }

  /**
   * Updates the color preview from the current model value
   */
  private void updatePreview(@Nullable Color color) {
    previewColor = color;
    repaint();
  }


}
