version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    registries: "*"

registries:
  itemis:
    type: maven-repository
    url: https://artifacts.itemis.cloud/repository/maven-mps
