package test.de.slisson.mps.tables;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheBuilder;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import de.slisson.mps.tables.runtime.cells.TableEditor;
import de.slisson.mps.tables.runtime.cells.StickyHeaderPainter;
import org.junit.Assert;
import de.slisson.mps.tables.runtime.cells.EditorCell_GridCell;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.awt.Graphics;
import java.awt.Rectangle;
import com.intellij.openapi.application.ApplicationManager;

@MPSLaunch
public class StickyHeaders_BandCoversTableWidth_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCacheBuilder(StickyHeaders_BandCoversTableWidth_Test.class).projectPath(null).modelRef("r:53747654-8f0d-48ae-96f3-1e68e62f0a2f(test.de.slisson.mps.tables@tests)").reopenProject(false).build());

  public StickyHeaders_BandCoversTableWidth_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_StickyHeaders_BandCoversTableWidth() throws Throwable {
    new TestBody(this).testMethod();
  }

  /*package*/ static class TestBody extends BaseEditorTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("6525704942445775571", "");
      TableEditor table = FindTableEditor.getTableEditor(getEditorComponent());
      final StickyHeaderPainter painter = table.getStickyHeaderPainter();
      Assert.assertNotNull(painter);

      // the rows occupied by the column headers
      int top = Integer.MAX_VALUE;
      int bottom = Integer.MIN_VALUE;
      for (EditorCell_GridCell cell : ListSequence.fromList(table.getStickyCells())) {
        if (cell.isVerticallyStickyCell()) {
          top = Math.min(top, cell.getY());
          bottom = Math.max(bottom, cell.getY() + cell.getHeight());
        }
      }
      int left = table.getX();
      int right = table.getX() + table.getWidth();

      Color marker = new Color(255, 0, 255);
      BufferedImage image = new BufferedImage(right + 10, table.getY() + table.getHeight() + 10, BufferedImage.TYPE_INT_RGB);
      final Graphics g = image.getGraphics();
      g.setColor(marker);
      g.fillRect(0, 0, image.getWidth(), image.getHeight());

      // scrolled down by 5 pixels, so the column headers have to stick to the top of the view
      final Rectangle view = new Rectangle(0, top + 5, image.getWidth(), image.getHeight());
      ApplicationManager.getApplication().invokeAndWait(() -> getEditorComponent().getEditorContext().getRepository().getModelAccess().runReadAction(() -> painter.paint(g, view, Color.WHITE)));

      // every pixel of the band is painted over, including the parts of the table without a column header
      int notPainted = 0;
      for (int y = top + 5; y < bottom + 5; y++) {
        for (int x = left; x < right; x++) {
          if (image.getRGB(x, y) == marker.getRGB()) {
            notPainted++;
          }
        }
      }
      Assert.assertEquals(0, notPainted);

      // header cells without the sticky style ("ID") are inside the frozen rows too and must not be hidden by the band
      int unstyledHeaders = 0;
      int unstyledHeaderInk = 0;
      for (EditorCell_GridCell cell : ListSequence.fromList(table.getGridCells())) {
        if (!(cell.isStickyCell()) && cell.getY() >= top && cell.getY() + cell.getHeight() <= bottom) {
          unstyledHeaders++;
          for (int y = cell.getY() + 5 + 2; y < cell.getY() + cell.getHeight() + 5 - 2; y++) {
            for (int x = cell.getX() + 2; x < cell.getX() + cell.getWidth() - 2; x++) {
              if (image.getRGB(x, y) != Color.WHITE.getRGB() && image.getRGB(x, y) != marker.getRGB()) {
                unstyledHeaderInk++;
              }
            }
          }
        }
      }
      Assert.assertTrue(unstyledHeaders > 0);
      Assert.assertTrue(unstyledHeaderInk > 0);

      // nothing is painted below the band
      Assert.assertEquals(marker.getRGB(), image.getRGB(left, bottom + 5));
    }
  }
}
