package de.itemis.mps.utils.serializer.xml.serializer;

/*Generated by MPS */

import org.jdom2.Element;
import org.jetbrains.mps.openapi.model.SNode;

public class SerializerProcessor {
  public boolean postProcess(Element element, SNode node) {
    return true;
  }
  public void postProcessXMLRoot(Element xmlRoot) {
  }
}
