package de.q60.mps.virtualinterfaces.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class typeof_ThisExpression_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_ThisExpression_InferenceRule() {
  }
  public void applyRule(final SNode n, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    SNode concept = SLinkOperations.getTarget(SNodeOperations.getNodeAncestor(n, CONCEPTS.VirtualInterfaceImplementation$TX, false, false), LINKS.implementingConcept$nh6M);
    if ((concept == null)) {
      {
        SNode _nodeToCheck_1029348928467 = n;
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:0677cfe7-9421-4700-9f87-00f9f449dce1(de.q60.mps.virtualinterfaces.typesystem)", "2031504182169539430", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:0677cfe7-9421-4700-9f87-00f9f449dce1(de.q60.mps.virtualinterfaces.typesystem)", "2031504182169539437", true), (SNode) _quotation_createNode_dzbtrx_a1a0c0a0b0b(), _info_12389875345);
      }
    } else {
      {
        SNode _nodeToCheck_1029348928467 = n;
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:0677cfe7-9421-4700-9f87-00f9f449dce1(de.q60.mps.virtualinterfaces.typesystem)", "6594016813169220076", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:0677cfe7-9421-4700-9f87-00f9f449dce1(de.q60.mps.virtualinterfaces.typesystem)", "6594016813169219508", true), (SNode) _quotation_createNode_dzbtrx_a1a0c0a0a1a1(concept), _info_12389875345);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.ThisExpression$Rt;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
  private static SNode _quotation_createNode_dzbtrx_a1a0c0a0b0b() {
    SNode quotedNode_1 = null;
    SNodeBuilder nb = new SNodeBuilder(null, null).init(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x1185ff468caL, "NullType"));
    quotedNode_1 = nb.getResult();
    return quotedNode_1;
  }
  private static SNode _quotation_createNode_dzbtrx_a1a0c0a0a1a1(Object parameter_1) {
    SNode quotedNode_2 = null;
    SNodeBuilder nb = new SNodeBuilder(null, null).init(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, "jetbrains.mps.lang.smodel"), 0x108f968b3caL, "SNodeType"));
    quotedNode_2 = nb.getResult();
    SNodeAccessUtil.setReferenceTarget(quotedNode_2, MetaAdapterFactory.getReferenceLink(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x108f968b3caL, 0x1090e46ca51L, "concept"), (SNode) parameter_1);
    return quotedNode_2;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept VirtualInterfaceImplementation$TX = MetaAdapterFactory.getConcept(0x2b95e1754fca48d9L, 0x982b58c954a32b02L, 0x5b82a75adfd9bde4L, "de.q60.mps.virtualinterfaces.structure.VirtualInterfaceImplementation");
    /*package*/ static final SConcept ThisExpression$Rt = MetaAdapterFactory.getConcept(0x2b95e1754fca48d9L, 0x982b58c954a32b02L, 0x5b82a75adfe75370L, "de.q60.mps.virtualinterfaces.structure.ThisExpression");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink implementingConcept$nh6M = MetaAdapterFactory.getReferenceLink(0x2b95e1754fca48d9L, 0x982b58c954a32b02L, 0x5b82a75adfd9bde4L, 0x5b82a75adfde08cdL, "implementingConcept");
  }
}
