package nl.f1re.testing.examples.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.DefaultExtensionDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.structure.ExtensionPoint;

public class ExtensionDescriptor extends DefaultExtensionDescriptor {
  public ExtensionDescriptor() {
    super(Arrays.asList(new ExtensionPoint("nl.f1re.testing.examples.TestExtensionPoint")), Arrays.asList(new TestExtension()));
  }
}
