package de.itemis.mps.editor.diagram.runtime.plugin;

/*Generated by MPS */

import jetbrains.mps.logging.Logger;
import com.intellij.openapi.project.Project;
import java.nio.file.Paths;
import de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell;
import org.jetbrains.mps.openapi.module.SRepository;
import jetbrains.mps.ide.project.ProjectHelper;
import com.intellij.openapi.ui.Messages;
import com.intellij.notification.NotificationType;
import com.intellij.notification.NotificationAction;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.notification.Notification;
import java.awt.Toolkit;
import java.awt.Image;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.awt.image.BufferedImage;
import java.awt.Graphics2D;
import javax.imageio.ImageIO;
import java.io.IOException;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorComponent;
import jetbrains.mps.nodeEditor.EditorSettings;
import java.awt.Color;
import org.apache.batik.svggen.SVGGraphics2D;
import java.awt.Dimension;
import de.itemis.mps.editor.celllayout.runtime.BorderPainter;
import jetbrains.mps.openapi.editor.cells.CellTraversalUtil;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.nodeEditor.EditorCell_WithComponent;
import javax.swing.JComponent;
import java.awt.Graphics;
import com.intellij.ide.actions.RevealFileAction;

public class ImageExportUtil {
  private static final Logger LOG = Logger.getLogger(ImageExportUtil.class);

  public static final String DEFAULT_SCREENSHOT_FOLDER = "cell-screenshots";

  public static String getScreenShotsFolder(Project ideaProject) {
    return Paths.get(ideaProject.getBasePath(), DEFAULT_SCREENSHOT_FOLDER).toString();
  }

  public static String exportAsPNG(RootDiagramECell diagramCell, SRepository repository) {
    Project ideaProject = ProjectHelper.toIdeaProject(ProjectHelper.getProject(repository));
    final String path = Paths.get(ideaProject.getBasePath(), DEFAULT_SCREENSHOT_FOLDER).toString();
    final String filename = getFullPathName(diagramCell, path, ".png");
    if (!(saveAsPNG(diagramCell, filename))) {
      Messages.showErrorDialog(ideaProject, "Destination: " + filename, "Failed to save image");
    }

    NotificationUtil.showNotification("PNG Exported", "The PNG file has been exported to " + filename, NotificationType.INFORMATION, new NotificationAction("Reveal") {
      @Override
      public void actionPerformed(@NotNull AnActionEvent event, @NotNull Notification notification) {
        ImageExportUtil.openBrowser(filename);
      }
    }, new NotificationAction("Copy Image to Clipboard") {
      @Override
      public void actionPerformed(@NotNull AnActionEvent event, @NotNull Notification notification) {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.createImage(filename);
        TransferableImage ti = new TransferableImage(image);
        toolkit.getSystemClipboard().setContents(ti, null);
      }
    }, new NotificationAction("Copy Path to Clipboard") {
      @Override
      public void actionPerformed(@NotNull AnActionEvent event, @NotNull Notification notification) {
        StringSelection sl = new StringSelection(filename);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(sl, null);
      }
    });
    return filename;
  }

  private static boolean saveAsPNG(RootDiagramECell cell, final String filename) {
    try {
      new File(filename).getParentFile().mkdirs();
      BufferedImage image = new BufferedImage(cell.getWidth(), cell.getHeight(), BufferedImage.TYPE_INT_RGB);
      Graphics2D g = image.createGraphics();
      paintCell(g, cell);

      try {
        ImageIO.write(image, "png", new File(filename));
      } catch (IOException ex) {
        if (LOG.isErrorLevel()) {
          LOG.error("Failed to write image", ex);
        }
      }
    } catch (Exception ex) {
      if (LOG.isErrorLevel()) {
        LOG.error("Failed to save image", ex);
      }
      return false;
    }
    return true;
  }

  public static String exportAsSVG(RootDiagramECell diagramCell, SRepository repository) {
    Project ideaProject = ProjectHelper.toIdeaProject(ProjectHelper.getProject(repository));
    final String path = getScreenShotsFolder(ideaProject);
    final String filename = getFullPathName(diagramCell, path, ".svg");
    if (!(saveAsSVG(diagramCell, repository, path))) {
      Messages.showErrorDialog(ideaProject, "Destination: " + filename, "Failed to save SVG");
      return null;
    }
    showSVGExportedNotification(filename, ideaProject);
    return filename;
  }

  public static boolean saveAsSVG(final EditorCell cell, SRepository repository, String path) {
    Project ideaProject = ProjectHelper.toIdeaProject(ProjectHelper.getProject(repository));

    if ((path == null || path.length() == 0)) {
      path = getScreenShotsFolder(ideaProject);
    }
    new File(path).mkdirs();
    final String filename = getFullPathName(cell, path, ".svg");
    try {
      final File targetFile = new File(filename);

      repository.getModelAccess().executeCommandInEDT(() -> {
        try {
          SVGGenerator.generateImage((Graphics2D g) -> paintCell(g, cell), targetFile);
        } catch (Exception ex) {
          if (LOG.isErrorLevel()) {
            LOG.error("Failed to generate image due to exception: " + ex.toString());
          }
        }
      });
    } catch (Exception ex) {
      Messages.showErrorDialog(ideaProject, "Failed to save image: " + ex.getMessage(), "Failed to save image");
      return false;
    }
    return true;
  }

  public static void paintCell(final Graphics2D g, EditorCell cell) {
    EditorComponent.turnOnAliasingIfPossible(g);
    g.setFont(EditorSettings.getInstance().getDefaultEditorFont());
    Color backgroundColor = cell.getEditorComponent().getStyleRegistry().getEditorBackground();
    g.setColor(backgroundColor);
    int width = cell.getX() + cell.getWidth();
    int height = cell.getY() + cell.getHeight();

    g.fillRect(0, 0, width, height);

    if (g.getClass() == SVGGraphics2D.class) {
      ((SVGGraphics2D) g).setSVGCanvasSize(new Dimension(width, height));
    }

    g.translate(-cell.getX(), -cell.getY());
    cell.paint(g);
    BorderPainter painter = new BorderPainter();
    painter.paint(g, as_ieged4_a1a0o0o(cell.getEditorComponent(), EditorComponent.class));
    Iterable<jetbrains.mps.openapi.editor.cells.EditorCell> descendants = CellTraversalUtil.iterateTree(cell, cell, true);
    Sequence.fromIterable(descendants).ofType(EditorCell_WithComponent.class).visitAll((it) -> {
      JComponent comp = it.getComponent();
      Graphics gc = g.create(comp.getX(), comp.getY(), comp.getWidth(), comp.getHeight());
      try {
        comp.paint(gc);
      } finally {
        gc.dispose();
      }
    });
  }

  public static void showSVGExportedNotification(final String filename, final Project ideaProject) {
    NotificationUtil.showNotification("SVG Exported", "The SVG file has been exported to " + filename, NotificationType.INFORMATION, new NotificationAction("Reveal") {
      @Override
      public void actionPerformed(@NotNull AnActionEvent event, @NotNull Notification notification) {
        ImageExportUtil.openBrowser(filename);
      }
    }, new NotificationAction("Copy Path to Clipboard") {
      @Override
      public void actionPerformed(@NotNull AnActionEvent event, @NotNull Notification notification) {
        StringSelection sl = new StringSelection(filename);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(sl, null);
      }
    });
  }

  private static String getFullPathName(EditorCell cell, String path, String suffix) {
    return Paths.get(path, cell.getCellId() + suffix).toString();
  }

  public static void openBrowser(String filename) {
    RevealFileAction.openFile(new File(filename));
  }
  private static <T> T as_ieged4_a1a0o0o(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
