package de.itemis.mps.editor.diagram.runtime.substitute;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.cells.SubstituteInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.Objects;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import de.slisson.mps.hacks.editor.SubstituteUtil;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class SubstituteInfoFactory {

  private EditorContext myEditorContext;
  private SNode mySNode;

  public SubstituteInfoFactory(EditorContext context, SNode node) {
    myEditorContext = context;
    mySNode = node;
  }

  public SubstituteInfo forEmptyList(SNode parent, SNode linkdDeclaration) {
    return forChild(parent, null, linkdDeclaration);
  }

  public SubstituteInfo forChild(SNode child) {
    if (SNodeOperations.getParent(child) == null) {
      return null;
    }
    return forChild(SNodeOperations.getParent(child), child, SNodeOperations.getContainingLink(child));
  }

  public SubstituteInfo forChild(SNode parent, SNode child) {
    return forChild(parent, child, SNodeOperations.getContainingLink(child));
  }

  public SubstituteInfo forChildLink(SNode parent, SNode linkDeclaration) {
    return forChild(parent, null, linkDeclaration);
  }


  public SubstituteInfo forChild(SNode parent, SNode child, final SNode linkDeclaration) {
    Iterable<SContainmentLink> links = SNodeOperations.getConcept(parent).getContainmentLinks();
    SContainmentLink link = Sequence.fromIterable(links).findFirst((it) -> Objects.equals(it.getName(), SPropertyOperations.getString(linkDeclaration, PROPS.name$MnvL)));
    return forChild(parent, child, link);
  }

  public SubstituteInfo forChild(SNode parent, SNode child, SContainmentLink link) {
    return SubstituteUtil.forChild(myEditorContext, parent, child, link);
  }

  public SubstituteInfo composite(SubstituteInfo... parts) {
    return new CompositeSubstituteInfo(parts);
  }

  public SubstituteInfo filter(SubstituteInfo info, ISubstituteActionFilter filter) {
    return new FilteringSubstituteInfo(info, filter);
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
