package com.mbeddr.mpsutil.blutil.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class MatchExpression_Constraints extends BaseConstraintsDescriptor {
  /*package*/ MatchExpression_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.MatchExpression$Uh, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept MatchExpression$Uh = MetaAdapterFactory.getConcept(0x63e0e5665131447eL, 0x90e312ea330e1a00L, 0x2bc62943b5c60704L, "com.mbeddr.mpsutil.blutil.structure.MatchExpression");
  }
}
