package de.slisson.mps.tables.runtime.plugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import de.slisson.mps.tables.runtime.selection.TableRangeSelection;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import jetbrains.mps.smodel.SNodeMatcher;
import jetbrains.mps.lang.core.behavior.BaseConcept__BehaviorDescriptor;

public interface DataTransformer {
  int getPriority();

  boolean isApplicable(SNode node, EditorContext editorContext);

  void setTable(SNode table);

  SNode fromString(String data);

  default String asString(TableRangeSelection selection, final SNode node, EditorContext editorContext) {
    if ((node == null)) {
      return "";
    }

    EditorCell nodeCell = ListSequence.fromList(selection.getSelectedGridCells()).findFirst((it) -> {
      SNode gridNode = it.getSNode();
      return ListSequence.fromList(SNodeOperations.getNodeDescendants(gridNode, null, true, new SAbstractConcept[]{})).any(new _FunctionTypes._return_P1_E0<Boolean, SNode>() {
        public Boolean invoke(SNode gridNode) {
          return new SNodeMatcher().match(gridNode, node);
        }
      });
    });
    if (nodeCell == null) {
      // fall back to string representation
      return BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(node);
    }

    String text = nodeCell.renderText().getText();
    return text;
  }
}
