package test.de.q60.mps.shadowmodels.examples;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheBuilder;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;

@MPSLaunch
public class Entity2Java_reduce_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCacheBuilder(Entity2Java_reduce_Test.class).projectPath(null).modelRef("r:d779ef4d-b8f4-4bf2-9b31-f1c1d22129f6(test.de.q60.mps.shadowmodels.examples@tests)").reopenProject(null).build());

  public Entity2Java_reduce_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_checkOutput() throws Throwable {
    new TestBody(this).test_checkOutput();
  }

  /*package*/ static class TestBody extends BaseTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    protected void initTestNodes() {
      prepareTestNodes("5383735579112775711", "5383735579112777202");
    }

    public void test_checkOutput() throws Exception {
      initTestNodes();
      runWithinCommand(() -> TransformationTestUtil.runTest(getAnnotatedNode("input"), getAnnotatedNode("expectedOutput"), new SNodePointer("r:37e85211-427f-482e-b697-cf3275c6d596(de.q60.mps.shadowmodels.examples.entities.transformations)", "1109773557182659393"), ListSequence.fromListAndArray(new ArrayList<SModuleReference>(), PersistenceFacade.getInstance().createModuleReference("ca32b5fa-caea-4f97-9686-6f60d4d677d4(de.q60.mps.shadowmodels.examples.entities)")), false));
    }

  }
}
