package de.itemis.mps.editor.diagram.demo.elk.editor;

/*Generated by MPS */

import jetbrains.mps.logging.Logger;
import jetbrains.mps.editor.runtime.style.AbstractStyleClass;
import jetbrains.mps.editor.runtime.descriptor.EditorBuilderEnvironment;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class BoxTestStyleSheet_StyleSheet {
  private static final Logger LOG = Logger.getLogger(BoxTestStyleSheet_StyleSheet.class);
  public static class BoxNodesStyleClass extends AbstractStyleClass {
    public BoxNodesStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.getInstance().<Integer>getAttribute("de.itemis.mps.editor.diagram", "diagram-layout-priority"), _StyleParameter_QueryFunction_civtkl_a0a());
    }

    private Integer _StyleParameter_QueryFunction_civtkl_a0a() {
      if (LOG.isErrorLevel()) {
        LOG.error("Index:" + SNodeOperations.getIndexInParent(getNode()));
      }
      return SNodeOperations.getIndexInParent(getNode());
    }
  }
  public static class BoxEdgesStyleClass extends AbstractStyleClass {
    public BoxEdgesStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
    }

  }
  public static class BoxLabelsStyleClass extends AbstractStyleClass {
    public BoxLabelsStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
    }

  }
}
