package de.itemis.mps.editor.diagram.demo.elk.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.style.AbstractStyleClass;
import jetbrains.mps.editor.runtime.descriptor.EditorBuilderEnvironment;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.openapi.editor.cells.EditorCell;

public class ShrinkingTestStyleSheet_StyleSheet {
  public static class ShrinkingNodesStyleClass extends AbstractStyleClass {
    public ShrinkingNodesStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
    }

  }
  public static class ShrinkingEdgesStyleClass extends AbstractStyleClass {
    public ShrinkingEdgesStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
    }

  }
  public static class ShrinkingLabelsStyleClass extends AbstractStyleClass {
    public ShrinkingLabelsStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
    }

  }
}
