package de.slisson.mps.tables.demolang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class TestSuite_SubstituteMenu extends SubstituteMenuBase {
  public TestSuite_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for TestSuite. Generated from implicit smart reference attribute.", new SNodePointer("r:41c447ce-0fca-4a98-ad9f-dc62c992880f(de.slisson.mps.tables.demolang.structure)", "1397920687865838768")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_bkchax_a(), CONCEPTS.TestSuite$cR));
    result.add(new SMP_Subconcepts_bkchax_b());
    return result;
  }

  public class SMP_ReferenceScope_bkchax_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_bkchax_a() {
      super(CONCEPTS.TestSuite$cR, LINKS.rule$x3sx, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_bkchax_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_bkchax_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "TestSuite", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.TestSuite$cR);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept TestSuite$cR = MetaAdapterFactory.getConcept(0x2d56439e634d4d25L, 0x9d30963e89ecda48L, 0x136669758869bcb0L, "de.slisson.mps.tables.demolang.structure.TestSuite");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink rule$x3sx = MetaAdapterFactory.getReferenceLink(0x2d56439e634d4d25L, 0x9d30963e89ecda48L, 0x136669758869bcb0L, 0x136669758869bcbdL, "rule");
  }
}
