package de.slisson.mps.tables.runtime.cells;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import de.slisson.mps.tables.runtime.gridmodel.Grid;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout;
import java.util.Iterator;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.Objects;
import de.slisson.mps.tables.runtime.gridmodel.IGridElement;
import de.slisson.mps.tables.runtime.gridmodel.EditorCellGridLeaf;
import jetbrains.mps.openapi.editor.cells.CellTraversalUtil;

public abstract class AbstractTableEditor extends EditorCell_Collection {

  protected Grid myGrid;

  public AbstractTableEditor(EditorContext context, SNode snode, CellLayout layout, Grid grid) {
    super(context, snode, layout, null);
    myGrid = grid;
    myGrid.setSourceCell(this);
  }

  public Grid getGrid() {
    return myGrid;
  }

  public void initChilds(ChildsTracker childsTracker) {
    addRegisteredGridCellsToThis(myGrid, childsTracker);
    {
      Iterator<EditorCell> cell_it = SetSequence.fromSet(childsTracker.getRegisteredCells()).iterator();
      EditorCell cell_var;
      while (cell_it.hasNext()) {
        cell_var = cell_it.next();
        if (cell_var instanceof PartialTableEditor) {
          ((PartialTableEditor) cell_var).memorizeOriginalParent();
          EditorCell_Collection originalParent = ((EditorCell_Collection) cell_var.getParent());
          if (originalParent != null) {
            originalParent.removeCell(((jetbrains.mps.nodeEditor.cells.EditorCell) cell_var));
          }
          addEditorCell(cell_var);
        }
      }
    }
    sortChildren();
  }

  public void sortChildren() {
    List<jetbrains.mps.nodeEditor.cells.EditorCell> unsorted = Sequence.fromIterable(Sequence.fromArray(getCells())).toList();
    List<jetbrains.mps.nodeEditor.cells.EditorCell> sorted = ListSequence.fromList(unsorted).sort((it) -> getRow(it), true).toList();
    if (!(Objects.equals(unsorted, sorted))) {
      ListSequence.fromList(unsorted).visitAll((it) -> removeCell(it));
      ListSequence.fromList(sorted).visitAll((it) -> addEditorCell(it));
    }
  }

  private int getRow(EditorCell cell) {
    if (cell instanceof EditorCell_GridCell) {
      return ((EditorCell_GridCell) cell).getGridPosition().getY();
    }
    int row = -1;
    if (cell instanceof jetbrains.mps.openapi.editor.cells.EditorCell_Collection) {
      for (EditorCell child : Sequence.fromIterable((jetbrains.mps.openapi.editor.cells.EditorCell_Collection) cell)) {
        row = Math.max(row, getRow(child));
      }
    }
    return row;
  }

  protected void addRegisteredGridCellsToThis(Grid grid, ChildsTracker childsTracker) {
    for (IGridElement element : Sequence.fromIterable(grid)) {
      if (element instanceof Grid) {
        Grid childGrid = ((Grid) element);
        if (childGrid.getSourceCell() != null) {
          return;
        }
        addRegisteredGridCellsToThis(childGrid, childsTracker);
      } else if (element instanceof EditorCellGridLeaf) {
        EditorCell cell = check_kwxx98_a0a0a0a0a31(as_kwxx98_a0a0a0a0a0a31(element, EditorCellGridLeaf.class));
        if (cell != null && allowAddGridCell(cell, childsTracker)) {
          if (!(CellTraversalUtil.isAncestor(this, cell))) {
            if (cell.getParent() != null) {
              ((EditorCell_Collection) cell.getParent()).removeCell(((jetbrains.mps.nodeEditor.cells.EditorCell) cell));
            }
            addEditorCell(cell);
          }
        }
      }
    }
  }

  protected boolean allowAddGridCell(EditorCell cell, ChildsTracker childsTracker) {
    return childsTracker.isRegistered(cell);
  }

  protected void addGridCellsWithoutParentToThis(Grid grid) {
    for (IGridElement element : Sequence.fromIterable(grid)) {
      if (element instanceof Grid) {
        Grid childGrid = ((Grid) element);
        addGridCellsWithoutParentToThis(childGrid);
      } else if (element instanceof EditorCellGridLeaf) {
        EditorCell cell = check_kwxx98_a0a0a0a0a71(as_kwxx98_a0a0a0a0a0a71(element, EditorCellGridLeaf.class));
        if (cell != null) {
          if (cell.getParent() == null || (cell.getParent().getSNode() == getSNode() && Objects.equals(cell.getParent().getCellId(), this.getCellId()) && cell.getParent() != this)) {
            addEditorCell(cell);
          }
        }
      }
    }
  }
  @Override
  public void setCellId(String string) {
    super.setCellId(string);
    addGridCellsWithoutParentToThis(myGrid);
  }

  @Override
  public void requestRelayout() {
    super.requestRelayout();
    check_kwxx98_a1a02(getParent(), this);
  }

  private static EditorCell check_kwxx98_a0a0a0a0a31(EditorCellGridLeaf checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getEditorCell();
    }
    return null;
  }
  private static EditorCell check_kwxx98_a0a0a0a0a71(EditorCellGridLeaf checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getEditorCell();
    }
    return null;
  }
  private static void check_kwxx98_a1a02(EditorCell_Collection checkedDotOperand, AbstractTableEditor checkedDotThisExpression) {
    if (null != checkedDotOperand) {
      checkedDotOperand.requestRelayout();
    }

  }
  private static <T> T as_kwxx98_a0a0a0a0a0a31(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
  private static <T> T as_kwxx98_a0a0a0a0a0a71(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
