package de.itemis.model.merge.simple.demo.plugin;

/*Generated by MPS */

import de.itemis.model.merge.runtime.runtime.ConceptMergeSpec;
import java.util.Arrays;
import de.itemis.model.merge.runtime.runtime.PropertyMerger;
import de.itemis.model.merge.runtime.runtime.BuiltInRight;
import de.itemis.model.merge.runtime.runtime.ConceptChildMerger;
import de.itemis.model.merge.runtime.runtime.ConceptRefMerger;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class ConceptWithProperty_mergepolicy_ConceptWithProperty_ga54dx_b extends ConceptMergeSpec {

  public ConceptWithProperty_mergepolicy_ConceptWithProperty_ga54dx_b() {
    super(CONCEPTS.ConceptWithProperty$lL, Arrays.<PropertyMerger>asList(new BuiltInRight(PROPS.mergeid$5Lst), new BuiltInRight(PROPS.virtualPackage$EkXl), new BuiltInRight(PROPS.data$hkMD)), Arrays.<ConceptChildMerger>asList(), Arrays.<ConceptRefMerger>asList());
  }


  private String innerId(SNode instance) {
    return SPropertyOperations.getString(instance, PROPS.data$hkMD);
  }

  @Override
  public String id(SNode node) {
    return this.innerId(node);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ConceptWithProperty$lL = MetaAdapterFactory.getConcept(0xe50b05006fd74c7fL, 0xa7309d841358ca2bL, 0x30904120a9a19b20L, "de.itemis.model.simple.demo.property.structure.ConceptWithProperty");
  }

  private static final class PROPS {
    /*package*/ static final SProperty mergeid$5Lst = MetaAdapterFactory.getProperty(0xe50b05006fd74c7fL, 0xa7309d841358ca2bL, 0x30904120a9a19b20L, 0x7a1db2d8f7d99e52L, "mergeid");
    /*package*/ static final SProperty virtualPackage$EkXl = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL, 0x115eca8579fL, "virtualPackage");
    /*package*/ static final SProperty data$hkMD = MetaAdapterFactory.getProperty(0xe50b05006fd74c7fL, 0xa7309d841358ca2bL, 0x30904120a9a19b20L, 0x30904120a9a19b21L, "data");
  }
}
