[versions]
# For published MPS releases adjust the version below and the dependency in [libraries]
mps = "262.9437.193"

[libraries]
# For published releases adjust the version in [versions] and use this dependency:
# mps = { module = "com.jetbrains:mps", version.ref = "mps" }
mps = { module = "com.jetbrains.mps:mps-prerelease", version.ref = "mps" }
jbr = { module = "com.jetbrains.mps:mps-jbr", version.ref = "mps" }
