package de.itemis.mps.compare.pattern.baselang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.TransformationMenu;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new AnnotationTarget_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new GetOperation_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new InitPartAccessorOperation_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new IsMatchOperation_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new MatchOperation_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new MatchResultType_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new NamedGetTarget_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new PatternHint_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<TransformationMenu> getDeclaredDefaultTransformationMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<TransformationMenu>singletonList(new PatternHint_Create_Contribution());
      default:
    }
    return Collections.<TransformationMenu>emptyList();
  }
  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex2.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new AnnotationTarget_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new InitPartAccessorOperation_SubstituteMenu());
      case 2:
        return Collections.<SubstituteMenu>singletonList(new PatternHint_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x93c76ef17979084L), MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x93c76ef17957eb1L), MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x5bfa3e4528f2a811L), MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x93c76ef179517c7L), MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x186d97e0b986cd07L), MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x93c76ef1794694dL), MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x93c76ef17957ec3L), MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x93c76ef17a26793L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).seal();
  private static final ConceptSwitchIndex conceptIndex2 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x93c76ef17979084L), MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x5bfa3e4528f2a811L), MetaIdFactory.conceptId(0x36590f48d68b4c16L, 0xbfbac769260bbac0L, 0x93c76ef17a26793L)).seal();
}
