package com.mbeddr.mpsutil.blutil.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ConceptSwitchStatement_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
    _context.getBuilder().build((SNode) SLinkOperations.getTarget(_context.getNode(), LINKS.expr$XWv9));

    for (SNode switchCase : SLinkOperations.getChildren(_context.getNode(), LINKS.cases$rkI)) {
      _context.getBuilder().emitIfJump(_context.getBuilder().before(switchCase), "63e0e566-5131-447e-90e3-12ea330e1a00/r:bed974e6-d268-4395-932a-5674ee845678(com.mbeddr.mpsutil.blutil/com.mbeddr.mpsutil.blutil.dataFlow)/3622390367882302665");
    }
    _context.getBuilder().emitJump(_context.getBuilder().before(SLinkOperations.getTarget(_context.getNode(), LINKS.default$GCsX)), "63e0e566-5131-447e-90e3-12ea330e1a00/r:bed974e6-d268-4395-932a-5674ee845678(com.mbeddr.mpsutil.blutil/com.mbeddr.mpsutil.blutil.dataFlow)/4749636953794126064");

    for (SNode switchCase : SLinkOperations.getChildren(_context.getNode(), LINKS.cases$rkI)) {
      _context.getBuilder().build((SNode) switchCase);
    }
    _context.getBuilder().build((SNode) SLinkOperations.getTarget(_context.getNode(), LINKS.default$GCsX));
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expr$XWv9 = MetaAdapterFactory.getContainmentLink(0x63e0e5665131447eL, 0x90e312ea330e1a00L, 0x78777fea72a4fbd4L, 0x78777fea72a4fbd5L, "expr");
    /*package*/ static final SContainmentLink cases$rkI = MetaAdapterFactory.getContainmentLink(0x63e0e5665131447eL, 0x90e312ea330e1a00L, 0x78777fea72a4fbd4L, 0x78777fea72a4fbdaL, "cases");
    /*package*/ static final SContainmentLink default$GCsX = MetaAdapterFactory.getContainmentLink(0x63e0e5665131447eL, 0x90e312ea330e1a00L, 0x78777fea72a4fbd4L, 0x2c94d9a5bf5ab80eL, "default");
  }
}
