package com.mbeddr.mpsutil.modellisteners.runtime;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;

public interface IRootRemovedListener extends IRootListener {
  void rootRemoved(SNode root, SModel model);
}
