package de.itemis.model.merge.simple.demo.annotated.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAnnotatable = createDescriptorForAnnotatable();
  /*package*/ final ConceptDescriptor myConceptAnnotation = createDescriptorForAnnotation();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAnnotatable, myConceptAnnotation);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Annotatable:
        return myConceptAnnotatable;
      case LanguageConceptSwitch.Annotation:
        return myConceptAnnotation;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAnnotatable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("de.itemis.model.merge.simple.demo.annotated", "Annotatable", 0xc527d4ce1a24433bL, 0xb1ec929a89de103aL, 0xf045b38d3fc98b1L);
    b.class_(false, false, true);
    b.origin("r:ab430aa7-ae71-487c-8661-09a68deffd67(de.itemis.model.merge.simple.demo.annotated.structure)/1082090110108604593");
    b.version(3);
    b.property("value", 0xf045b38d3fc98b4L).type(PrimitiveTypeId.INTEGER).origin("1082090110108604596").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("de.itemis.model.merge.simple.demo.annotated", "Annotation", 0xc527d4ce1a24433bL, 0xb1ec929a89de103aL, 0xf045b38d3fcf011L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.lang.core.structure.NodeAttribute
    b.super_(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L);
    b.origin("r:ab430aa7-ae71-487c-8661-09a68deffd67(de.itemis.model.merge.simple.demo.annotated.structure)/1082090110108626961");
    b.version(3);
    b.property("id", 0xf045b38d3fcf68aL).type(PrimitiveTypeId.STRING).origin("1082090110108628618").done();
    b.property("value", 0x639e9b48d4815cbeL).type(PrimitiveTypeId.INTEGER).origin("7178345593180347582").done();
    b.alias("annotation");
    return b.create();
  }
}
