package test.de.itemis.mps.editor.diagram.lang.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import jetbrains.mps.logging.Logger;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import de.itemis.mps.editor.diagram.runtime.model.EditorCell_DiagramElement;
import de.itemis.mps.editor.diagram.runtime.ContextVariables;
import de.itemis.mps.editor.diagram.runtime.model.SNodeEdgeAccessor;
import de.itemis.mps.editor.diagram.runtime.DiagramUtil;
import de.itemis.mps.editor.diagram.runtime.shape.IShape;
import de.itemis.mps.editor.diagram.runtime.model.IConnectionEndpointReference;
import de.itemis.mps.editor.diagram.runtime.model.EndpointUtil;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;
import jetbrains.mps.baseLanguage.tuples.runtime.MultiTuple;
import de.itemis.mps.editor.diagram.runtime.model.IConnectionEndpoint_Internal;
import de.itemis.mps.editor.diagram.runtime.model.Box;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.annotations.Nullable;
import java.util.List;
import de.itemis.mps.editor.diagram.runtime.model.IDiagramElementAccessor;
import de.itemis.mps.editor.diagram.runtime.model.IAccessorFactory;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import de.itemis.mps.editor.diagram.runtime.model.Port;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import de.itemis.mps.editor.diagram.runtime.jgraph.MyGraph;
import de.itemis.mps.editor.diagram.runtime.jgraph.DiagramCreationContext;
import de.itemis.mps.editor.diagram.runtime.jgraph.ElkLayouter;
import de.itemis.mps.editor.diagram.runtime.model.AbstractBoxAccessor;
import java.util.Collections;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import de.itemis.mps.editor.diagram.runtime.model.AbstractEdgeAccessor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import org.jetbrains.mps.openapi.language.SContainmentLink;

/*package*/ class Compilation_CellModel_Diagram_Connector_EditorBuilder_a extends AbstractEditorBuilder {
  private static final Logger LOG = Logger.getLogger(Compilation_CellModel_Diagram_Connector_EditorBuilder_a.class);
  @NotNull
  private SNode myNode;

  public Compilation_CellModel_Diagram_Connector_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createDiagramConnector_1();
  }

  private EditorCell createDiagramConnector_0(final EditorContext editorContext, final SNode node) {

    final Wrappers._T<EditorCell_DiagramElement> diagramCell = new Wrappers._T<EditorCell_DiagramElement>(null);

    ContextVariables.withValue("thisNode", node, () -> {
      final ContextVariables _variablesContext = ContextVariables.getCurrent();
      SNodeEdgeAccessor accessor = new SNodeEdgeAccessor(node, null) {
        private EditorCell startRoleCell = DiagramUtil.getCellIfNotEmpty(new Inline_Builder_20e91b_a0a(editorContext, node).createCell());
        private EditorCell endRoleCell = DiagramUtil.getCellIfNotEmpty(new Inline_Builder_20e91b_a0a_0(editorContext, node).createCell());
        private IShape endShape = new CompilationShape(true);
        private IShape startShape = new CompilationShape(true);

        private IConnectionEndpointReference endpointFrom = EndpointUtil.createEndpointReferenceForPortSafe(EndpointUtil.createEndpointReferenceForIdSafe("id"), "portName");
        private IConnectionEndpointReference endpointTo = (true ? EndpointUtil.createEndpointReferenceForIdSafe("id") : EndpointUtil.createEndpointReferenceForPortSafe(EndpointUtil.createEndpointReferenceForIdSafe("id"), "portName"));

        {
          boolean reverse = true;
          if (reverse) {

            {
              Tuples._2<IConnectionEndpointReference, IConnectionEndpointReference> _tmp_8lm3y7_b0b0i0a0a1a2a3a8 = MultiTuple.<IConnectionEndpointReference,IConnectionEndpointReference>from(endpointTo, endpointFrom);
              endpointFrom = _tmp_8lm3y7_b0b0i0a0a1a2a3a8._0();
              endpointTo = _tmp_8lm3y7_b0b0i0a0a1a2a3a8._1();
            }
            {
              Tuples._2<EditorCell, EditorCell> _tmp_8lm3y7_c0b0i0a0a1a2a3a8 = MultiTuple.<EditorCell,EditorCell>from(endRoleCell, startRoleCell);
              startRoleCell = _tmp_8lm3y7_c0b0i0a0a1a2a3a8._0();
              endRoleCell = _tmp_8lm3y7_c0b0i0a0a1a2a3a8._1();
            }
            {
              Tuples._2<IShape, IShape> _tmp_8lm3y7_d0b0i0a0a1a2a3a8 = MultiTuple.<IShape,IShape>from(endShape, startShape);
              startShape = _tmp_8lm3y7_d0b0i0a0a1a2a3a8._0();
              endShape = _tmp_8lm3y7_d0b0i0a0a1a2a3a8._1();
            }
          }
        }

        @Override
        public void writeFrom(IConnectionEndpoint_Internal endpoint) {
          writeFrom(EndpointUtil.getSNode(endpoint), EndpointUtil.getBox(endpoint), EndpointUtil.getPortName(endpoint));
        }
        public void writeFrom(final SNode targetNode, Box targetDNode, final String port) {
          if (LOG.isDebugLevel()) {
            LOG.debug("node:" + SNodeOperations.present(node));
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("targetDNode:" + targetDNode);
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("targetNode:" + SNodeOperations.present(targetNode));
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("port:" + port);
          }
        }
        @Override
        public void writeTo(IConnectionEndpoint_Internal endpoint) {
          writeTo(EndpointUtil.getSNode(endpoint), EndpointUtil.getBox(endpoint), EndpointUtil.getPortName(endpoint));
        }
        public void writeTo(final SNode targetNode, Box targetDNode, final String port) {
          if (LOG.isDebugLevel()) {
            LOG.debug("node:" + SNodeOperations.present(node));
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("targetDNode:" + targetDNode);
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("targetNode:" + SNodeOperations.present(targetNode));
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("port:" + port);
          }
        }
        @Override
        public boolean canWriteFrom(IConnectionEndpoint_Internal endpoint) {
          return canWriteFrom(EndpointUtil.getSNode(endpoint), EndpointUtil.getBox(endpoint), EndpointUtil.getPortName(endpoint));
        }
        public boolean canWriteFrom(final SNode targetNode, Box targetDNode, final String port) {
          if (LOG.isDebugLevel()) {
            LOG.debug("node:" + SNodeOperations.present(node));
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("targetDNode:" + targetDNode);
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("targetNode:" + SNodeOperations.present(targetNode));
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("port:" + port);
          }
          return true;
        }
        @Override
        public boolean canWriteTo(IConnectionEndpoint_Internal endpoint) {
          return canWriteTo(EndpointUtil.getSNode(endpoint), EndpointUtil.getBox(endpoint), EndpointUtil.getPortName(endpoint));
        }
        public boolean canWriteTo(final SNode targetNode, Box targetDNode, final String port) {
          if (LOG.isDebugLevel()) {
            LOG.debug("node:" + SNodeOperations.present(node));
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("targetDNode:" + targetDNode);
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("targetNode:" + SNodeOperations.present(targetNode));
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("port:" + port);
          }
          return true;
        }
        private boolean nodeCondition_20e91b_a0() {
          if (LOG.isDebugLevel()) {
            LOG.debug("editor context:" + getEditorContext());
          }
          if (LOG.isDebugLevel()) {
            LOG.debug("node:" + SNodeOperations.present(myNode));
          }
          return true;
        }
        @Override
        public boolean pullAnnotations() {
          return nodeCondition_20e91b_a0();
        }

        @Override
        public IConnectionEndpointReference readFrom() {
          return endpointFrom;
        }
        @Override
        public IConnectionEndpointReference readTo() {
          return endpointTo;
        }
        @Override
        public EditorCell getEndRoleCell() {
          return endRoleCell;
        }
        public IShape getEndShape() {
          return endShape;
        }
        @Override
        public EditorCell getStartRoleCell() {
          return startRoleCell;
        }
        public IShape getStartShape() {
          return startShape;
        }
        @Override
        public boolean isCurved() {
          return true;
        }
        @Override
        public String getEdgeStyle() {
          return "elbowEdgeStyle";
        }

        @Nullable
        @Override
        public Double getStartShapeSize() {
          return ((double) (100));
        }
        @Nullable
        @Override
        public Double getEndShapeSize() {
          return ((double) (100));
        }
        public List<? extends IDiagramElementAccessor> getElements(IAccessorFactory accessorFactory) {
          final List<IDiagramElementAccessor> elements = new ArrayList<IDiagramElementAccessor>();
          for (SNode e : ListSequence.fromList(SLinkOperations.getChildren(node, LINKS.smodelAttribute$KJ43))) {
            elements.addAll(accessorFactory.fromSNode(e));
          }
          for (final SNode parameterObject : ListSequence.fromListAndArray(new ArrayList<SNode>(), new Object() {
            public SNode query() {
              return SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xaff569ad098d414aL, 0xaa2396963959392cL, 0x21236ffd758cc99bL, "test.de.itemis.mps.editor.diagram.lang.structure.Box"));
            }
          }.query())) {
            ContextVariables.withParentAndValue(_variablesContext, "parameterObject", parameterObject, new Runnable() {
              public void run() {
                final ContextVariables _variablesContext = ContextVariables.getCurrent();
                final EditorCell editorCell = new Inline_Builder_20e91b_a1a(editorContext, parameterObject).createCell();

                final List<Port> ports = new ArrayList<Port>();
                {
                  Port port = new Port("myPort");
                  port.setRelativeX(0.0);
                  port.setRelativeY(0.5);
                  port.setWidth(12);
                  port.setHeight(12);
                  port.setShape(new CompilationShape(true));
                  port.setTooltipCell(new Inline_Builder_20e91b_a0b0(editorContext, node).createCell());
                  Style style = new StyleImpl();
                  MyGraph rootGraph = DiagramCreationContext.getRootGraph();
                  if (port.getBox() != null && rootGraph != null) {
                    ElkLayouter layouter = (ElkLayouter) rootGraph.getRootDiagramModel().getLayouter();
                    layouter.addPortsStyle(style, port.getBox().getAccessor().getId());
                  }
                  ports.add(port);
                }

                final IShape shape = new CompilationShape(true);

                AbstractBoxAccessor accessor = new AbstractBoxAccessor(EndpointUtil.createAccessorKeyForSNode(((SNode) _variablesContext.getValue("parameterObject")))) {
                  @Nullable
                  public SNode getSNode() {
                    return parameterObject;
                  }
                  public void delete() {
                  }
                  @NotNull
                  @Override
                  public List<EditorCell> getContentCells() {
                    return Collections.singletonList(editorCell);
                  }
                  @NotNull
                  @Override
                  public List<Port> getPorts() {
                    return ports;
                  }
                  @Override
                  public boolean isPreservePortOrder() {
                    return false;
                  }
                  @Override
                  public IShape getShape() {
                    return shape;
                  }
                  @Override
                  public boolean allowConnectionsToBox() {
                    return true;
                  }
                  @NotNull
                  @Override
                  public Iterable<SNode> getNavigationTargets() {
                    Iterable<SNode> result = Sequence.fromIterable(Collections.<SNode>emptyList());
                    result = Sequence.fromIterable(result).concat(Sequence.fromIterable(Sequence.<SNode>singleton(((SNode) _variablesContext.getValue("parameterObject")))));
                    return result;
                  }
                  @Override
                  public boolean allowScaling() {
                    return true;
                  }
                  public boolean canDrop(Object data) {
                    return true;
                  }
                  public void drop(Object data) {
                    if (LOG.isDebugLevel()) {
                      LOG.debug("Data:" + data);
                    }
                  }
                };
                accessor.setRootCell(editorCell);
                Style style = new StyleImpl();
                style.set(StyleAttributes.getInstance().<String>getAttribute("de.itemis.mps.editor.diagram.styles", "__align-enum"), "LEFT");
                style.set(StyleAttributes.getInstance().<Boolean>getAttribute("de.itemis.mps.editor.diagram.styles", "__align-buttons"), true);
                style.set(StyleAttributes.getInstance().<Boolean>getAttribute("de.itemis.mps.editor.diagram.styles", "__fit-size-button"), true);
                style.set(StyleAttributes.getInstance().<Boolean>getAttribute("de.itemis.mps.editor.diagram.styles", "__reorder-ports-button"), true);
                style.set(StyleAttributes.getInstance().<Boolean>getAttribute("de.itemis.mps.editor.diagram.styles", "__open-node-buttons"), true);
                style.set(StyleAttributes.getInstance().<Boolean>getAttribute("de.itemis.mps.editor.diagram.styles", "__relayout-edges-button"), true);
                accessor.setStyle(style);
                MyGraph rootGraph = DiagramCreationContext.getRootGraph();
                if (rootGraph != null) {
                  ElkLayouter layouter = (ElkLayouter) rootGraph.getRootDiagramModel().getLayouter();
                  layouter.addNodesStyle(accessor.getStyle(), accessor.getId());
                }

                elements.add(accessor);
              }
            });
          }
          for (final SNode parameterObject : ListSequence.fromListAndArray(new ArrayList<SNode>(), new Object() {
            public SNode query() {
              return SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xaff569ad098d414aL, 0xaa2396963959392cL, 0x21236ffd758e4248L, "test.de.itemis.mps.editor.diagram.lang.structure.Edge"));
            }
          }.query())) {
            ContextVariables.withParentAndValue(_variablesContext, "parameterObject", parameterObject, new Runnable() {
              public void run() {
                final ContextVariables _variablesContext = ContextVariables.getCurrent();
                final EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, parameterObject);
                editorCell.setCellId("transformedGraphElement_c0_0" + "." + ((SNode) _variablesContext.getValue("parameterObject")));

                final EditorCell labelCell = DiagramUtil.getCellIfNotEmpty(new Inline_Builder_20e91b_a2a(editorContext, parameterObject).createCell());
                final EditorCell startRoleCell = DiagramUtil.getCellIfNotEmpty(new Inline_Builder_20e91b_a0c0(editorContext, parameterObject).createCell());
                final EditorCell endRoleCell = DiagramUtil.getCellIfNotEmpty(new Inline_Builder_20e91b_a0c0_0(editorContext, parameterObject).createCell());
                if (labelCell != null) {
                  editorCell.addEditorCell(labelCell);
                }
                if (startRoleCell != null) {
                  editorCell.addEditorCell(startRoleCell);
                }
                if (endRoleCell != null) {
                  editorCell.addEditorCell(endRoleCell);
                }

                final IShape startShape = new CompilationShape(true);
                final IShape endShape = new CompilationShape(true);
                AbstractEdgeAccessor accessor = new AbstractEdgeAccessor(EndpointUtil.createAccessorKeyForSNode(((SNode) _variablesContext.getValue("parameterObject")))) {
                  @Override
                  public void writeFrom(IConnectionEndpoint_Internal endpoint) {
                    writeFrom(EndpointUtil.getSNode(endpoint), EndpointUtil.getBox(endpoint), EndpointUtil.getPortName(endpoint));
                  }
                  public void writeFrom(final SNode targetNode, Box targetDNode, final String port) {
                    if (LOG.isDebugLevel()) {
                      LOG.debug("node:" + SNodeOperations.present(node));
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("targetDNode:" + targetDNode);
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("targetNode:" + SNodeOperations.present(targetNode));
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("port:" + port);
                    }
                  }
                  @Override
                  public void writeTo(IConnectionEndpoint_Internal endpoint) {
                    writeTo(EndpointUtil.getSNode(endpoint), EndpointUtil.getBox(endpoint), EndpointUtil.getPortName(endpoint));
                  }
                  public void writeTo(final SNode targetNode, Box targetDNode, final String port) {
                    if (LOG.isDebugLevel()) {
                      LOG.debug("node:" + SNodeOperations.present(node));
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("targetDNode:" + targetDNode);
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("targetNode:" + SNodeOperations.present(targetNode));
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("port:" + port);
                    }
                  }
                  @Override
                  public boolean canWriteFrom(IConnectionEndpoint_Internal endpoint) {
                    return canWriteFrom(EndpointUtil.getSNode(endpoint), EndpointUtil.getBox(endpoint), EndpointUtil.getPortName(endpoint));
                  }
                  public boolean canWriteFrom(final SNode targetNode, Box targetDNode, final String port) {
                    if (LOG.isDebugLevel()) {
                      LOG.debug("node:" + SNodeOperations.present(node));
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("targetDNode:" + targetDNode);
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("targetNode:" + SNodeOperations.present(targetNode));
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("port:" + port);
                    }
                    return true;
                  }
                  @Override
                  public boolean canWriteTo(IConnectionEndpoint_Internal endpoint) {
                    return canWriteTo(EndpointUtil.getSNode(endpoint), EndpointUtil.getBox(endpoint), EndpointUtil.getPortName(endpoint));
                  }
                  public boolean canWriteTo(final SNode targetNode, Box targetDNode, final String port) {
                    if (LOG.isDebugLevel()) {
                      LOG.debug("node:" + SNodeOperations.present(node));
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("targetDNode:" + targetDNode);
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("targetNode:" + SNodeOperations.present(targetNode));
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("port:" + port);
                    }
                    return true;
                  }
                  private boolean nodeCondition_20e91b_a2a() {
                    if (LOG.isDebugLevel()) {
                      LOG.debug("editor context:" + getEditorContext());
                    }
                    if (LOG.isDebugLevel()) {
                      LOG.debug("node:" + SNodeOperations.present(myNode));
                    }
                    return true;
                  }
                  @Override
                  public boolean pullAnnotations() {
                    return nodeCondition_20e91b_a2a();
                  }
                  @Override
                  public IConnectionEndpointReference readFrom() {
                    return EndpointUtil.createEndpointReferenceForIdSafe("id");
                  }
                  @Override
                  public IConnectionEndpointReference readTo() {
                    return EndpointUtil.createEndpointReferenceForIdSafe("id");
                  }
                  @Override
                  public IShape getStartShape() {
                    return startShape;
                  }
                  @Override
                  public IShape getEndShape() {
                    return endShape;
                  }
                  @Nullable
                  @Override
                  public Double getStartShapeSize() {
                    return ((double) (100));
                  }
                  @Nullable
                  @Override
                  public Double getEndShapeSize() {
                    return ((double) (100));
                  }
                  @Override
                  public EditorCell getLabelCell() {
                    return labelCell;
                  }
                  @Override
                  public EditorCell getStartRoleCell() {
                    return startRoleCell;
                  }
                  @Override
                  public EditorCell getEndRoleCell() {
                    return endRoleCell;
                  }
                  @Override
                  public void delete() {
                  }
                  @Nullable
                  public SNode getSNode() {
                    return parameterObject;
                  }

                  @Override
                  public boolean canSplit(@NotNull final SAbstractConcept concept) {
                    return true;
                  }
                  @Override
                  public void split(@NotNull final Box boxToInsert) {
                    if (LOG.isDebugLevel()) {
                      LOG.debug("box to insert:" + boxToInsert);
                    }
                  }
                  @NotNull
                  @Override
                  public Iterable<SNode> getNavigationTargets() {
                    Iterable<SNode> result = Sequence.fromIterable(Collections.<SNode>emptyList());
                    result = Sequence.fromIterable(result).concat(Sequence.fromIterable(Sequence.<SNode>singleton(((SNode) _variablesContext.getValue("parameterObject")))));
                    return result;
                  }
                  @Override
                  public boolean anySideAllowedFrom() {
                    return true;
                  }
                  @Override
                  public boolean anySideAllowedTo() {
                    return true;
                  }
                  @Override
                  public boolean isCurved() {
                    return true;
                  }
                  @Override
                  public String getEdgeStyle() {
                    return "elbowEdgeStyle";
                  }
                  public boolean canDrop(Object data) {
                    if (LOG.isDebugLevel()) {
                      LOG.debug("data:" + data);
                    }
                    return true;
                  }
                  public void drop(Object data) {
                    if (LOG.isDebugLevel()) {
                      LOG.debug("data:" + data);
                    }
                  }
                };
                accessor.setRootCell(editorCell);
                MyGraph rootGraph = DiagramCreationContext.getRootGraph();
                if (rootGraph != null) {
                  ElkLayouter layouter = (ElkLayouter) rootGraph.getRootDiagramModel().getLayouter();
                  layouter.addEdgesStyle(accessor.getStyle(), accessor.getId());
                  layouter.addLabelsStyle(accessor.getStyle(), accessor.getId());
                }

                elements.add(accessor);
              }
            });
          }
          for (SNode e : Sequence.fromIterable(new Object() {
            public Iterable<SNode> query() {
              if (LOG.isDebugLevel()) {
                LOG.debug("node:" + SNodeOperations.present(node));
              }
              return ListSequence.fromList(new ArrayList<SNode>());
            }
          }.query())) {
            elements.addAll(accessorFactory.fromSNode(e, false));
          }
          return elements;
        }

        @Override
        public void delete() {
        }

        @NotNull
        @Override
        public Iterable<SNode> getNavigationTargets() {
          Iterable<SNode> result = Sequence.fromIterable(Collections.<SNode>emptyList());
          result = Sequence.fromIterable(result).concat(Sequence.fromIterable(Sequence.<SNode>singleton(((SNode) _variablesContext.getValue("thisNode")))));
          return result;
        }
        @Override
        public boolean canSplit(@NotNull final SAbstractConcept concept) {
          return true;
        }
        @Override
        public void split(@NotNull final Box boxToInsert) {
          if (LOG.isDebugLevel()) {
            LOG.debug("box to insert:" + boxToInsert);
          }
        }
        @Override
        public boolean anySideAllowedFrom() {
          return true;
        }
        @Override
        public boolean anySideAllowedTo() {
          return true;
        }
        public boolean canDrop(Object data) {
          if (LOG.isDebugLevel()) {
            LOG.debug("data:" + data);
          }
          return true;
        }
        public void drop(Object data) {
          if (LOG.isDebugLevel()) {
            LOG.debug("data:" + data);
          }
        }
      };

      EditorCell label = DiagramUtil.getCellIfNotEmpty(new Inline_Builder_20e91b_a0(editorContext, node).createCell());

      EditorCell editorCell = label;
      MyGraph rootGraph = DiagramCreationContext.getRootGraph();
      if (editorCell != null && rootGraph != null) {
        ElkLayouter layouter = (ElkLayouter) rootGraph.getRootDiagramModel().getLayouter();
        layouter.addLabelsStyle(editorCell.getStyle(), accessor.getId());
      }

      accessor.setLabelCell(label);

      diagramCell.value = new EditorCell_DiagramElement(editorContext, node, accessor);
      editorCell = diagramCell.value;
      editorCell.setCellId("DiagramConnector_20e91b_a");
      editorCell.setBig(true);
      setCellContext(editorCell);

      if (rootGraph != null) {
        ElkLayouter layouter = (ElkLayouter) rootGraph.getRootDiagramModel().getLayouter();
        layouter.addEdgesStyle(diagramCell.value.getStyle(), accessor.getId());
      }

      if (accessor.getLabelCell() != null) {
        diagramCell.value.addEditorCell(accessor.getLabelCell());
      }
      if (accessor.getStartRoleCell() != null) {
        diagramCell.value.addEditorCell(accessor.getStartRoleCell());
      }
      if (accessor.getEndRoleCell() != null) {
        diagramCell.value.addEditorCell(accessor.getEndRoleCell());
      }
    });

    return diagramCell.value;
  }
  private EditorCell createDiagramConnector_1() {
    return createDiagramConnector_0(getEditorContext(), getNode());
  }
  /*package*/ static class Inline_Builder_20e91b_a0a extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_20e91b_a0a(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createConstant_0();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createConstant_0() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "role");
      editorCell.setCellId("Constant_20e91b_a0a0");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  /*package*/ static class Inline_Builder_20e91b_a0a_0 extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_20e91b_a0a_0(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createConstant_1();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createConstant_1() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "role");
      editorCell.setCellId("Constant_20e91b_a0a0_0");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  /*package*/ static class Inline_Builder_20e91b_a0 extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_20e91b_a0(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createConstant_2();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createConstant_2() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "label cell");
      editorCell.setCellId("Constant_20e91b_a0a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  /*package*/ static class Inline_Builder_20e91b_a1a extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_20e91b_a1a(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createConstant_3();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createConstant_3() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "My content");
      editorCell.setCellId("Constant_20e91b_a0b0");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  /*package*/ static class Inline_Builder_20e91b_a0b0 extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_20e91b_a0b0(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createConstant_4();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createConstant_4() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "my tooltip");
      editorCell.setCellId("Constant_20e91b_a0a1a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  /*package*/ static class Inline_Builder_20e91b_a0c0 extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_20e91b_a0c0(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createConstant_5();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createConstant_5() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "role");
      editorCell.setCellId("Constant_20e91b_a0a2a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  /*package*/ static class Inline_Builder_20e91b_a0c0_0 extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_20e91b_a0c0_0(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createConstant_6();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createConstant_6() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "role");
      editorCell.setCellId("Constant_20e91b_a0a2a_0");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  /*package*/ static class Inline_Builder_20e91b_a2a extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_20e91b_a2a(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createConstant_7();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createConstant_7() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "label cell");
      editorCell.setCellId("Constant_20e91b_a0c0");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink smodelAttribute$KJ43 = MetaAdapterFactory.getContainmentLink(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL, 0x47bf8397520e5942L, "smodelAttribute");
  }
}
