package com.mbeddr.mpsutil.intentions.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class DescriptionUpdater {
  public static SNode updateIntention(SNode declaration) {
    SNode f = SLinkOperations.getTarget(declaration, LINKS.descriptionFunction$xRc1);
    SNode l = ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(f, LINKS.body$e68K), LINKS.statement$53DE)).last();
    String s = SectionAnnotation__BehaviorDescriptor.generateCaptionWithSectionPrefix_id24lzbKWiSKe.invoke(new IAttributeDescriptor.NodeAttribute(CONCEPTS.SectionAnnotation$yF).get(declaration), "");
    if (SNodeOperations.isInstanceOf(l, CONCEPTS.ExpressionStatement$O8)) {
      SNodeOperations.replaceWithAnother(l, createExpressionStatement_sttleu_a0a0a3a0(s, SLinkOperations.getTarget(SNodeOperations.cast(l, CONCEPTS.ExpressionStatement$O8), LINKS.expression$5L7M)));
    }
    for (SNode r : ListSequence.fromList(SNodeOperations.getNodeDescendants(SLinkOperations.getTarget(f, LINKS.body$e68K), CONCEPTS.ReturnStatement$lt, false, new SAbstractConcept[]{}))) {
      SNode ex = SLinkOperations.getTarget(r, LINKS.expression$eJ92);
      SNodeOperations.replaceWithAnother(ex, createPlusExpression_sttleu_a0a1a4a0(s, SLinkOperations.getTarget(r, LINKS.expression$eJ92)));
    }
    SNodeOperations.deleteNode(new IAttributeDescriptor.NodeAttribute(CONCEPTS.SectionAnnotation$yF).get(declaration));
    return declaration;
  }

  public static SNode updateAction(SNode declaration) {
    String caption = (isEmptyString(SPropertyOperations.getString(declaration, PROPS.caption$k5xp)) ? "" : SPropertyOperations.getString(declaration, PROPS.caption$k5xp));
    String newCaption = SectionAnnotation__BehaviorDescriptor.generateCaptionWithSectionPrefix_id24lzbKWiSKe.invoke(new IAttributeDescriptor.NodeAttribute(CONCEPTS.SectionAnnotation$yF).get(declaration), caption);
    SPropertyOperations.assign(declaration, PROPS.caption$k5xp, newCaption);
    SNodeOperations.deleteNode(new IAttributeDescriptor.NodeAttribute(CONCEPTS.SectionAnnotation$yF).get(declaration));
    return declaration;
  }
  private static SNode createExpressionStatement_sttleu_a0a0a3a0(String p0, SNode p1) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.ExpressionStatement$O8);
    {
      SNodeBuilder n1 = n0.forChild(LINKS.expression$5L7M).init(CONCEPTS.PlusExpression$k0);
      {
        SNodeBuilder n2 = n1.forChild(LINKS.leftExpression$sEj).init(CONCEPTS.StringLiteral$xu);
        n2.setProperty(PROPS.value$w7MM, p0);
      }
      {
        SNodeBuilder n3 = n1.forChild(LINKS.rightExpression$nvX).init(CONCEPTS.ParenthesizedExpression$Ws);
        n3.forChild(LINKS.expression$TlhM).initNode(p1, CONCEPTS.Expression$mB, true);
      }
    }
    return n0.getResult();
  }
  private static SNode createPlusExpression_sttleu_a0a1a4a0(String p0, SNode p1) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.PlusExpression$k0);
    {
      SNodeBuilder n1 = n0.forChild(LINKS.leftExpression$sEj).init(CONCEPTS.StringLiteral$xu);
      n1.setProperty(PROPS.value$w7MM, p0);
    }
    {
      SNodeBuilder n2 = n0.forChild(LINKS.rightExpression$nvX).init(CONCEPTS.ParenthesizedExpression$Ws);
      n2.forChild(LINKS.expression$TlhM).initNode(p1, CONCEPTS.Expression$mB, true);
    }
    return n0.getResult();
  }
  private static boolean isEmptyString(String str) {
    return str == null || str.isEmpty();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink descriptionFunction$xRc1 = MetaAdapterFactory.getContainmentLink(0xd7a92d38f7db40d0L, 0x8431763b0c3c9f20L, 0x2303633a9c3cc675L, 0x2303633a9c3cd0a9L, "descriptionFunction");
    /*package*/ static final SContainmentLink body$e68K = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body");
    /*package*/ static final SContainmentLink statement$53DE = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement");
    /*package*/ static final SContainmentLink expression$5L7M = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression");
    /*package*/ static final SContainmentLink expression$eJ92 = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, 0xf8cc6bf96cL, "expression");
    /*package*/ static final SContainmentLink leftExpression$sEj = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11cL, "leftExpression");
    /*package*/ static final SContainmentLink rightExpression$nvX = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11bL, "rightExpression");
    /*package*/ static final SContainmentLink expression$TlhM = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfb4ed32b7fL, 0xfb4ed32b80L, "expression");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SectionAnnotation$yF = MetaAdapterFactory.getConcept(0xb92f861d0184446dL, 0xb88b6dcf0e070241L, 0x5123265c29d0499fL, "com.mbeddr.mpsutil.intentions.structure.SectionAnnotation");
    /*package*/ static final SConcept ExpressionStatement$O8 = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement");
    /*package*/ static final SConcept ReturnStatement$lt = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, "jetbrains.mps.baseLanguage.structure.ReturnStatement");
    /*package*/ static final SConcept PlusExpression$k0 = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7fbL, "jetbrains.mps.baseLanguage.structure.PlusExpression");
    /*package*/ static final SConcept StringLiteral$xu = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, "jetbrains.mps.baseLanguage.structure.StringLiteral");
    /*package*/ static final SConcept ParenthesizedExpression$Ws = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfb4ed32b7fL, "jetbrains.mps.baseLanguage.structure.ParenthesizedExpression");
    /*package*/ static final SConcept Expression$mB = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL, "jetbrains.mps.baseLanguage.structure.Expression");
  }

  private static final class PROPS {
    /*package*/ static final SProperty caption$k5xp = MetaAdapterFactory.getProperty(0x28f9e4973b424291L, 0xaeba0a1039153ab1L, 0x1181ca87c38L, 0x1189e8d9a59L, "caption");
    /*package*/ static final SProperty value$w7MM = MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value");
  }
}
