package de.itemis.model.merge.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AbstractMergeAction = 0;
  public static final int AbstractPolicy = 1;
  public static final int ActionCollectionFunctionLeftParam = 2;
  public static final int ActionCollectionFunctionRightParam = 3;
  public static final int ActionFunctionAutoParam = 4;
  public static final int ActionFunctionLeftParam = 5;
  public static final int ActionFunctionRefLeftParam = 6;
  public static final int ActionFunctionRefRightParam = 7;
  public static final int ActionFunctionRightParam = 8;
  public static final int Add = 9;
  public static final int Auto = 10;
  public static final int ChildPolicy = 11;
  public static final int ConceptMergingPolicy = 12;
  public static final int DeclarationPolicy = 13;
  public static final int Drop = 14;
  public static final int EmptyMergingPolicy = 15;
  public static final int IdFunction = 16;
  public static final int IdFunctionParam = 17;
  public static final int Keep = 18;
  public static final int Left = 19;
  public static final int ManualAction = 20;
  public static final int ManualCollectionAction = 21;
  public static final int ManualRefAction = 22;
  public static final int MergeAction = 23;
  public static final int MergingPolicy = 24;
  public static final int ModelMergingConfiguration = 25;
  public static final int ModelMergingPolicy = 26;
  public static final int MultiChildPolicy = 27;
  public static final int OptionalChildPolicy = 28;
  public static final int OptionalPolicy = 29;
  public static final int OptionalRefPolicy = 30;
  public static final int PropertyPolicy = 31;
  public static final int ReferencePolicy = 32;
  public static final int Right = 33;
  public static final int RootMergingPolicy = 34;
  public static final int SingeltonRefPolicy = 35;
  public static final int SingletonChildPolicy = 36;
  public static final int SingletonPolicy = 37;
  public static final int SubPolicyContainer = 38;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x539e893908ef497cL, 0xa5fd25dd10137a55L);
    builder.put(0x68dab8ecba0b7f38L, AbstractMergeAction);
    builder.put(0x1ed6b4fde1eeb12cL, AbstractPolicy);
    builder.put(0x1d6bf952b319c1abL, ActionCollectionFunctionLeftParam);
    builder.put(0x1d6bf952b321edceL, ActionCollectionFunctionRightParam);
    builder.put(0x302bf84bb18edf41L, ActionFunctionAutoParam);
    builder.put(0x1cd0c633f52ec89dL, ActionFunctionLeftParam);
    builder.put(0x7979086505d848L, ActionFunctionRefLeftParam);
    builder.put(0x79790865116ddfL, ActionFunctionRefRightParam);
    builder.put(0x1cd0c633f5300d63L, ActionFunctionRightParam);
    builder.put(0x74e2e0579b54de6bL, Add);
    builder.put(0x74e2e0579b2e78b7L, Auto);
    builder.put(0x3d71e5f153dd81bdL, ChildPolicy);
    builder.put(0x1a8b8d3e42de4bf5L, ConceptMergingPolicy);
    builder.put(0x74e2e0579b2effc2L, DeclarationPolicy);
    builder.put(0x74e2e0579b2e78b6L, Drop);
    builder.put(0x1a8b8d3e42de614eL, EmptyMergingPolicy);
    builder.put(0x630e54bf61025dc7L, IdFunction);
    builder.put(0x630e54bf61026838L, IdFunctionParam);
    builder.put(0x74e2e0579b55f155L, Keep);
    builder.put(0x1a8b8d3e42e44bcaL, Left);
    builder.put(0x1cd0c633f52d547bL, ManualAction);
    builder.put(0x1d6bf952b317b5e3L, ManualCollectionAction);
    builder.put(0x79790864a5c281L, ManualRefAction);
    builder.put(0x68dab8ecba0b4ed5L, MergeAction);
    builder.put(0x1a8b8d3e42de4bfaL, MergingPolicy);
    builder.put(0x58db1f6941b979a6L, ModelMergingConfiguration);
    builder.put(0x1a8b8d3e42dcce87L, ModelMergingPolicy);
    builder.put(0x74e2e0579b2f965fL, MultiChildPolicy);
    builder.put(0x3d71e5f1540a0132L, OptionalChildPolicy);
    builder.put(0x74e2e0579b2eb40bL, OptionalPolicy);
    builder.put(0x3d71e5f1540a013aL, OptionalRefPolicy);
    builder.put(0x1a8b8d3e42e44628L, PropertyPolicy);
    builder.put(0x3d71e5f153835848L, ReferencePolicy);
    builder.put(0x68dab8ecba0b4ed6L, Right);
    builder.put(0x732319fb4b32eae2L, RootMergingPolicy);
    builder.put(0x3d71e5f1540a0137L, SingeltonRefPolicy);
    builder.put(0x3d71e5f1540a012fL, SingletonChildPolicy);
    builder.put(0x74e2e0579b2f964bL, SingletonPolicy);
    builder.put(0x1ed6b4fde1c3243aL, SubPolicyContainer);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
