package de.itemis.mps.editor.diagram.runtime.plugin;

/*Generated by MPS */

import javax.swing.Icon;
import jetbrains.mps.ide.icons.IconLoadingUtil;

public class IconContainer {
  protected static Icon ICON_a0 = IconLoadingUtil.loadIcon("erDiagram.svg", IconContainer.class);
}
