package de.itemis.mps.editor.bool.runtime;

/*Generated by MPS */

import jetbrains.mps.logging.Logger;
import java.awt.Image;
import java.awt.image.ImageObserver;
import org.jetbrains.mps.openapi.model.SNode;
import java.awt.Graphics;
import jetbrains.mps.nodeEditor.EditorComponent;
import java.awt.Graphics2D;
import java.awt.BasicStroke;
import com.intellij.ui.JBColor;
import org.jetbrains.mps.openapi.module.SModule;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.util.MacrosFactory;
import jetbrains.mps.project.AbstractModule;
import jetbrains.mps.vfs.IFile;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.project.Solution;

public class CheckboxImages {
  private static final Logger LOG = Logger.getLogger(CheckboxImages.class);
  private Image myImageTrue;
  private Image myImageFalse;
  private double myWidthScaled;
  private double myHeightScaled;
  private boolean myIsChecked;
  private double myScaleTrue = 1.0;
  private double myScaleFalse = 1.0;

  private ImageObserver sizeObserver = new ImageObserver() {
    public boolean imageUpdate(Image img, int infoflags, int x, int y, int width, int height) {
      boolean widthOrHeightChanged = (infoflags & (HEIGHT | WIDTH)) != 0;
      if (widthOrHeightChanged) {
        updateSize();
      }
      return widthOrHeightChanged;
    }
  };

  public CheckboxImages() {
    updateSize();
  }

  public void setScaleTrue(double scale) {
    myScaleTrue = scale;
    updateSize();
  }

  public void setScaleFalse(double scale) {
    myScaleFalse = scale;
    updateSize();
  }

  public void setImageTrue(String path, SNode node) {
    myImageTrue = loadImage(path, node);
    updateSize();
  }

  public void setImageFalse(String path, SNode node) {
    myImageFalse = loadImage(path, node);
    updateSize();
  }

  protected void updateSize() {
    myWidthScaled = (int) Math.max(((myImageTrue == null ? 0 : myImageTrue.getWidth(sizeObserver) * myScaleTrue)), ((myImageFalse == null ? 0 : myImageFalse.getWidth(sizeObserver) * myScaleFalse)));
    myHeightScaled = (int) Math.max(((myImageTrue == null ? 0 : myImageTrue.getHeight(sizeObserver) * myScaleTrue)), ((myImageFalse == null ? 0 : myImageFalse.getHeight(sizeObserver) * myScaleFalse)));

    if (myWidthScaled == 0.0 && myHeightScaled == 0.0) {
      myWidthScaled = 12;
      myHeightScaled = 12;
    }

  }

  public void paint(Graphics g, int x, int y, EditorComponent editorComponent) {
    Image image = (myIsChecked ? myImageTrue : myImageFalse);
    double scale = (myIsChecked ? myScaleTrue : myScaleFalse);
    int widthUnscaled = (int) (myWidthScaled / scale);
    int heightUnscaled = (int) (myHeightScaled / scale);
    int widthScaledInt = ((int) myWidthScaled);
    int heightScaledInt = ((int) myHeightScaled);

    if (image != null) {
      int offsetX = (int) ((widthUnscaled - image.getWidth(sizeObserver)) / 2 * scale);
      int offsetY = (int) ((heightUnscaled - image.getHeight(sizeObserver)) / 2 * scale);

      g = g.create();
      Graphics2D g2d = as_tospi5_a0a4a7a32(g, Graphics2D.class);
      if (g2d != null) {
        g2d.scale(scale, scale);
        g2d.translate((x + offsetX) / scale, (y + offsetY) / scale);
      }
      g.drawImage(image, 0, 0, editorComponent);
      g.dispose();
    } else {

      int dcWidth = widthScaledInt - 1;
      int dcHeight = heightScaledInt - 1;
      int dcX = x;
      int dcY = y + 1;

      Graphics2D g2d = ((Graphics2D) g.create());
      g2d.setStroke(new BasicStroke(2));
      g2d.setColor(JBColor.BLACK);
      g2d.drawRect(dcX, dcY, dcWidth, dcHeight);

      if (myIsChecked) {
        g2d.drawLine(dcX + 4, dcY + 4, dcX + dcWidth - 4, dcY + dcHeight - 4);
        g2d.drawLine(dcX + 4, dcY + dcWidth - 4, dcX + dcHeight - 4, dcY + 4);
      }
      g2d.dispose();
    }
  }

  public void setChecked(boolean newValue) {
    myIsChecked = newValue;
  }

  public int getWidth() {
    return (int) myWidthScaled;
  }

  public int getHeight() {
    return (int) myHeightScaled;
  }

  private static String expandIconPath(String path, SNode sourceNode) {
    SModule module = findAnchorModule(SNodeOperations.getModel(SNodeOperations.asNode(SNodeOperations.getConcept(sourceNode))));
    return (module != null ? MacrosFactory.forModule(module).expandPath(path) : null);
  }

  private static Image loadImage(String fileName, SNode sourceNode) {
    if (fileName == null) {
      return null;
    }
    AbstractModule module = findAnchorModule(SNodeOperations.getModel(SNodeOperations.asNode(SNodeOperations.getConcept(sourceNode))));
    if (module == null) {
      return null;
    }
    fileName = MacrosFactory.forModule((SModule) module).expandPath(fileName);

    IFile imageFile = module.getFileSystem().getFile(fileName);
    if (imageFile.exists()) {
      try {
        return Toolkit.getDefaultToolkit().getImage(imageFile.getUrl());
      } catch (MalformedURLException e) {
        if (LOG.isErrorLevel()) {
          LOG.error("Failed to load checkbox image", e);
        }
      }
    }
    return null;
  }

  private static AbstractModule findAnchorModule(SModel model) {
    SModule module = model.getModule();
    if (module instanceof Language || module instanceof Solution) {
      return (AbstractModule) module;
    } else {
      return null;
    }
  }

  private static <T> T as_tospi5_a0a4a7a32(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
