package de.itemis.mps.editor.celllayout.layout;

/*Generated by MPS */

import de.itemis.mps.editor.celllayout.boxmodel.Size;
import de.itemis.mps.editor.celllayout.boxmodel.Bounds;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.Set;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import java.util.HashSet;

public class LayoutableExtensions {
  public LayoutableExtensions() {
  }
  public static int getBaseline(final ILayoutable _this) {
    return _this.getY() + _this.getAscent();
  }
  public static void setBaseline(final ILayoutable _this, int baseline) {
    _this.setY(baseline - _this.getAscent());
  }
  public static int getMaxX(final ILayoutable _this) {
    return _this.getX() + _this.getWidth();
  }
  public static int getMaxY(final ILayoutable _this) {
    return _this.getY() + _this.getHeight();
  }
  public static Size getSize(final ILayoutable _this) {
    return new Size(_this.getWidth(), _this.getHeight());
  }
  public static Bounds getBounds(final ILayoutable _this) {
    return new Bounds(_this.getX(), _this.getY(), _this.getWidth(), _this.getHeight());
  }
  public static void visitAll(final ILayoutable _this, _FunctionTypes._void_P1_E0<? super ILayoutable> visitor) {
    if (_this == null) {
      return;
    }
    visitor.invoke(_this);

    if (_this instanceof ILayoutableContainer) {
      for (ILayoutable child : ListSequence.fromList(((ILayoutableContainer) _this).getChildren())) {
        LayoutableExtensions.visitAll(child, visitor);
      }
    }
  }
  public static void visitChanged(final ILayoutable _this, _FunctionTypes._void_P1_E0<? super ILayoutable> visitor) {
    if (_this == null) {
      return;
    }
    if (!(_this.isChanged())) {
      return;
    }
    visitor.invoke(_this);

    if (_this instanceof ILayoutableContainer) {
      for (ILayoutable child : ListSequence.fromList(((ILayoutableContainer) _this).getChildren())) {
        LayoutableExtensions.visitChanged(child, visitor);
      }
    }
  }
  public static ILayoutable commonParent(final ILayoutable _this, ILayoutable other) {
    Set<ILayoutable> ancestors = SetSequence.fromSet(new HashSet<ILayoutable>());
    for (ILayoutable l = _this; l != null; l = l.getParent()) {
      SetSequence.fromSet(ancestors).addElement(l);
    }
    for (ILayoutable l = other; l != null; l = l.getParent()) {
      if (SetSequence.fromSet(ancestors).contains(l)) {
        return l;
      }
    }
    return null;
  }
  public static boolean isAncestor(final ILayoutable _this, ILayoutable ancestor) {
    if (ancestor == _this) {
      return true;
    }
    ILayoutableContainer parent = _this.getParent();
    if (parent == null) {
      return false;
    }
    return LayoutableExtensions.isAncestor(parent, ancestor);
  }
  public static boolean isAncestorOf(final ILayoutable _this, ILayoutable descendant) {
    return LayoutableExtensions.isAncestor(descendant, _this);
  }
}
