package com.mbeddr.mpsutil.blutil.genutil.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.ConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.annotations.Nullable;

public final class LanguageConceptSwitch implements ConceptIndex {
  private final LanguageConceptIndex myIndex;
  public static final int IsInTestsExpression = 0;
  public static final int MappingExecuteOnceExpression = 1;
  public static final int MappingHasBeenExecutedExpression = 2;
  public static final int SetMappingHasBeenExecutedExpression = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x189537ea2a2844c9L, 0x91aaa8e68b3e1e1bL);
    builder.put(0x3b6fbbb39fd8eff9L, IsInTestsExpression);
    builder.put(0x3a78c54a7ab2af93L, MappingExecuteOnceExpression);
    builder.put(0x3a78c54a7a7f5254L, MappingHasBeenExecutedExpression);
    builder.put(0x3a78c54a7ab2af92L, SetMappingHasBeenExecutedExpression);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  @Override
  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }

  @Override
  public int index(@Nullable SAbstractConcept c, int missingValue) {
    return myIndex.index(c, missingValue);
  }
}
