package de.q60.mps.explorer.impl.pf;

/*Generated by MPS */

import de.q60.mps.polymorphicfunctions.runtime.PFModule;
import jetbrains.mps.logging.Logger;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import de.q60.mps.polymorphicfunctions.runtime.IFunctionImplementation;
import java.util.List;
import de.q60.mps.polymorphicfunctions.runtime.IParameterType;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import de.q60.mps.polymorphicfunctions.runtime.ParameterType_Classifier;
import de.q60.mps.polymorphicfunctions.runtime.IPFContext;
import de.q60.mps.polymorphicfunctions.runtime.ParameterList;
import de.q60.mps.explorer.pf.ExplorerElement;
import de.q60.mps.polymorphicfunctions.runtime.GroupPFContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import javax.swing.Icon;
import jetbrains.mps.openapi.editor.cells.EditorCell_Collection;
import jetbrains.mps.internal.collections.runtime.Sequence;
import de.q60.mps.polymorphicfunctions.runtime.SimplePriorityRule;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.openapi.editor.cells.CellAction;
import jetbrains.mps.nodeEditor.updater.UpdaterImpl;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import jetbrains.mps.ide.icons.GlobalIconManager;
import jetbrains.mps.openapi.editor.cells.KeyMap;
import jetbrains.mps.internal.collections.runtime.CollectionSequence;
import jetbrains.mps.openapi.editor.cells.KeyMapAction;
import java.util.Collections;
import de.slisson.mps.reflection.runtime.ReflectionUtil;
import jetbrains.mps.nodeEditor.cellMenu.CompositeSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SubstituteInfoPartExt;
import jetbrains.mps.openapi.editor.cells.SubstituteInfo;
import jetbrains.mps.openapi.editor.cells.SubstituteAction;
import jetbrains.mps.baseLanguage.tuples.runtime.MultiTuple;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cells.EditorCell_Property;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.nodeEditor.cells.ModelAccessor;
import jetbrains.mps.internal.collections.runtime.IterableUtils;
import jetbrains.mps.internal.collections.runtime.NotNullWhereFilter;
import jetbrains.mps.openapi.editor.cells.EditorCell_Label;
import jetbrains.mps.nodeEditor.cells.PropertyAccessor;
import jetbrains.mps.nodeEditor.cells.SPropertyAccessor;
import jetbrains.mps.icons.MPSIcons;
import jetbrains.mps.nodeEditor.cells.EditorCell_Error;
import jetbrains.mps.nodeEditor.cells.EditorCell_Component;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class PF_EditorCells extends PFModule {
  private static final Logger LOG = Logger.getLogger(PF_EditorCells.class);
  public static final PF_EditorCells INSTANCE = ((_FunctionTypes._return_P0_E0<PF_EditorCells>) () -> {
    try {
      return new PF_EditorCells();
    } catch (RuntimeException ex) {
      if (LOG.isErrorLevel()) {
        LOG.error("Failed to load " + PF_EditorCells.class.getName(), ex);
      }
      throw ex;
    }
  }).invoke();
  private PF_EditorCells() {
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(CellExplorerRoot.class));
      private List<String> contextIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.explorerContextGroup");
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/buildTrace_2";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof CellExplorerRoot)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return new Object() {
          public ExplorerElement groupCall(final IPFContext _PFcontext) {
            return ((ExplorerElement) _PFcontext.callFunction("de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace", new ParameterList(new Object[]{((CellExplorerRoot) _PFparameters.get(0)).editorComponent.getRootCell()})));
          }
        }.groupCall(new GroupPFContext(_PFcontext, "de.q60.mps.explorer.impl.pf.PF_EditorCells.cellExplorerGroup"));
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell.class));
      private List<String> contextIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.explorerContextGroup");
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/buildTrace_4";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        ExplorerElement te = new ExplorerElement();
        te.text = ((String) _PFcontext.callFunction("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new ParameterList(new Object[]{((EditorCell) _PFparameters.get(0))})));
        te.navigationTarget = () -> ((EditorCell) _PFparameters.get(0)).getSNode();
        te.icon = ((Icon) _PFcontext.callFunction("de.q60.mps.explorer.impl.pf.PF_EditorCells.getIcon", new ParameterList(new Object[]{((EditorCell) _PFparameters.get(0))})));
        te.detailViewRoot = ((EditorCell) _PFparameters.get(0));

        if (((EditorCell) _PFparameters.get(0)) instanceof EditorCell_Collection) {
          for (EditorCell child : Sequence.fromIterable(((EditorCell_Collection) ((EditorCell) _PFparameters.get(0))))) {
            te.addChild(child);
          }
        }

        return te;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    addPriorityRule(new SimplePriorityRule("de.q60.mps.explorer.impl.pf/PF_EditorCells/buildTrace_4", "de.q60.mps.explorer.pf/TraceBuilders_generic/buildTrace_10"));
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(jetbrains.mps.nodeEditor.cells.EditorCell.class));
      private List<String> contextIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.explorerContextGroup");
      private List<String> groupIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.detailView");
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/buildTrace_0";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof jetbrains.mps.nodeEditor.cells.EditorCell)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        ExplorerElement te = new ExplorerElement();
        te.text = ((String) _PFcontext.callFunction("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new ParameterList(new Object[]{((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0))})));
        te.icon = ((Icon) _PFcontext.callFunction("de.q60.mps.explorer.impl.pf.PF_EditorCells.getIcon", new ParameterList(new Object[]{((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0))})));
        te.expandByDefault = true;

        if (((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0)).getKeyMap() != null) {
          te.addChild(((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0)).getKeyMap());
        }

        if (((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0)).getSubstituteInfo() != null) {
          te.addChild("Substitute Info: ", ((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0)).getSubstituteInfo());
        }

        ExplorerElement teActions = new ExplorerElement();
        te.addChild(teActions);
        teActions.text = "Actions";
        teActions.expandByDefault = true;
        Iterable<CellActionType> availableActions = ((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0)).getAvailableActions();
        for (CellActionType actionType : Sequence.fromIterable(availableActions).sort((it) -> it.toString(), true)) {
          CellAction action = ((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0)).getAction(actionType);
          teActions.addChild(actionType + ": ", action);
        }

        ExplorerElement teDeps = new ExplorerElement();
        teDeps.text = "Dependencies";
        te.addChild(teDeps);
        UpdaterImpl updater = (UpdaterImpl) ((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0)).getEditorComponent().getUpdater();
        for (SNode relatedNode : SetSequence.fromSet(updater.getRelatedNodes(((jetbrains.mps.nodeEditor.cells.EditorCell) _PFparameters.get(0))))) {
          teDeps.addChild(relatedNode);
        }

        return te;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(SNode.class));
      private List<String> contextIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.explorerContextGroup");
      private List<String> groupIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.detailView");
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/buildTrace_1";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof SNode)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        ExplorerElement ee = new ExplorerElement();
        ee.text = ((String) _PFcontext.callFunction("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new ParameterList(new Object[]{((SNode) _PFparameters.get(0))})));
        ee.navigationTarget = () -> ((SNode) _PFparameters.get(0));
        ee.icon = GlobalIconManager.getInstance().getIconFor(((SNode) _PFparameters.get(0)));
        return ee;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(KeyMap.class));
      private List<String> contextIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.explorerContextGroup");
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/buildTrace_9";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof KeyMap)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        ExplorerElement te = new ExplorerElement();
        te.text = "Keymap";
        for (KeyMap.ActionKey actionKey : CollectionSequence.fromCollection(((KeyMap) _PFparameters.get(0)).getActionKeys())) {
          if (actionKey == null) {
            continue;
          }
          for (KeyMapAction action : CollectionSequence.fromCollection(((KeyMap) _PFparameters.get(0)).getActions(Collections.singleton(actionKey)))) {
            if (action == null) {
              continue;
            }
            te.addChild(((String) _PFcontext.callFunction("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new ParameterList(new Object[]{actionKey}))) + " -> ", action);
          }
        }
        return te;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(KeyMap.ActionKey.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/toString_10";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof KeyMap.ActionKey)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return ((String) ReflectionUtil.readField(KeyMap.ActionKey.class, ((KeyMap.ActionKey) _PFparameters.get(0)), "myModifiers")) + " + " + ((String) ReflectionUtil.readField(KeyMap.ActionKey.class, ((KeyMap.ActionKey) _PFparameters.get(0)), "myKeyCode")) + ((((Boolean) ReflectionUtil.readField(KeyMap.ActionKey.class, ((KeyMap.ActionKey) _PFparameters.get(0)), "myKeyTyped")) ? " typed" : " pressed"));
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(CompositeSubstituteInfo.class));
      private List<String> contextIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.explorerContextGroup");
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/buildTrace_12";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof CompositeSubstituteInfo)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        ExplorerElement te = new ExplorerElement();
        te.text = ((String) _PFcontext.callFunction("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new ParameterList(new Object[]{((CompositeSubstituteInfo) _PFparameters.get(0))})));
        te.expandByDefault = true;
        for (SubstituteInfoPartExt part : ((SubstituteInfoPartExt[]) ReflectionUtil.readField(CompositeSubstituteInfo.class, ((CompositeSubstituteInfo) _PFparameters.get(0)), "myExtParts"))) {
          te.addChild(part);
        }
        return te;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(SubstituteInfo.class));
      private List<String> contextIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.explorerContextGroup");
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/buildTrace_14";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof SubstituteInfo)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        ExplorerElement te = new ExplorerElement();
        te.text = ((String) _PFcontext.callFunction("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new ParameterList(new Object[]{((SubstituteInfo) _PFparameters.get(0))})));

        final ExplorerElement teActions = new ExplorerElement();
        te.addChild(teActions);
        teActions.text = "Actions";

        List<SubstituteAction> strictActions = ((SubstituteInfo) _PFparameters.get(0)).getMatchingActions("", true);
        List<SubstituteAction> nonStrictActions = ((SubstituteInfo) _PFparameters.get(0)).getMatchingActions("", false);

        Iterable<SubstituteAction> strictOnly = ListSequence.fromList(strictActions).subtract(ListSequence.fromList(nonStrictActions));
        Iterable<SubstituteAction> nonStrictOnly = ListSequence.fromList(nonStrictActions).subtract(ListSequence.fromList(strictActions));
        Iterable<SubstituteAction> both = ListSequence.fromList(strictActions).intersect(ListSequence.fromList(nonStrictActions));

        Sequence.fromIterable(both).select((it) -> MultiTuple.<String,SubstituteAction>from("", it)).concat(Sequence.fromIterable(strictOnly).select((it) -> MultiTuple.<String,SubstituteAction>from("[strict] ", it))).concat(Sequence.fromIterable(nonStrictOnly).select((it) -> MultiTuple.<String,SubstituteAction>from("[non-strict] ", it))).sort((it) -> it._0(), true).alsoSort((it) -> it._1().getMatchingText(""), true).visitAll((it) -> teActions.addChild(it._0(), it._1()));

        return te;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(SubstituteAction.class));
      private List<String> contextIds = ListSequence.fromListAndArray(new ArrayList<String>(), "de.q60.mps.explorer.pf.TraceBuilders_base.explorerContextGroup");
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/buildTrace_16";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof SubstituteAction)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        ExplorerElement te = new ExplorerElement();
        te.text = ((SubstituteAction) _PFparameters.get(0)).getMatchingText("") + "   |   " + ((SubstituteAction) _PFparameters.get(0)).getDescriptionText("");
        SNode iconNode = ((SubstituteAction) _PFparameters.get(0)).getIconNode("");
        if (iconNode != null) {
          te.icon = GlobalIconManager.getInstance().getIconFor(iconNode);
        }
        return te;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Constant.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/toString_18";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Constant)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return "constant[" + ((EditorCell_Constant) _PFparameters.get(0)).getText() + "]";
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Property.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/toString_19";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Property)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        SProperty role = ((SProperty) _PFcontext.callFunction("de.q60.mps.explorer.impl.pf.PF_EditorCells.getProperty", new ParameterList(new Object[]{((EditorCell_Property) _PFparameters.get(0))})));
        return "property[" + check_sog9z1_a0a0a0a1a91(check_sog9z1_a0a0a0a0b0t(role)) + "." + check_sog9z1_a0a0a1a91(role) + " = " + ((EditorCell_Property) _PFparameters.get(0)).getText() + "]";
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Property.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/toString_20";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Property)) {
          return false;
        }
        if (!(((EditorCell_Property) _PFparameters.get(0)).getModelAccessor() instanceof ModelAccessor.ReadOnly)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return "readOnlyModelAccess[" + ((EditorCell_Property) _PFparameters.get(0)).getText() + "]";
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    addPriorityRule(new SimplePriorityRule("de.q60.mps.explorer.impl.pf/PF_EditorCells/toString_20", "de.q60.mps.explorer.impl.pf/PF_EditorCells/toString_19"));
    myImplementations.put("de.q60.mps.explorer.pf.TraceBuilders_base.toString", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Collection.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/toString_22";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Collection)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        Iterable<EditorCell> children = ((EditorCell_Collection) _PFparameters.get(0));
        return "collection: " + IterableUtils.join(Sequence.fromIterable(children).select((it) -> ((String) _PFcontext.callFunction("de.q60.mps.explorer.impl.pf.PF_EditorCells.getStringInCollection", new ParameterList(new Object[]{it})))).where(new NotNullWhereFilter()), " ");
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getStringInCollection", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getStringInCollection_25";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return null;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getStringInCollection", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Label.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getStringInCollection_26";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Label)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return ((EditorCell_Label) _PFparameters.get(0)).getText();
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getStringInCollection", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Collection.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getStringInCollection_27";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Collection)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        Iterable<EditorCell> children = ((EditorCell_Collection) _PFparameters.get(0));
        return IterableUtils.join(Sequence.fromIterable(children).select((it) -> ((String) _PFcontext.callFunction("de.q60.mps.explorer.impl.pf.PF_EditorCells.getStringInCollection", new ParameterList(new Object[]{it})))).where(new NotNullWhereFilter()), " ");
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getProperty", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(Object.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getProperty_30";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof Object)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return null;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getProperty", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Property.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getProperty_31";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Property)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return ((SProperty) _PFcontext.callFunction("de.q60.mps.explorer.impl.pf.PF_EditorCells.getProperty", new ParameterList(new Object[]{((EditorCell_Property) _PFparameters.get(0)).getModelAccessor()})));
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getProperty", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(PropertyAccessor.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getProperty_32";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof PropertyAccessor)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return ((PropertyAccessor) _PFparameters.get(0)).getProperty();
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getProperty", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(SPropertyAccessor.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getProperty_33";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof SPropertyAccessor)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return ((SProperty) ReflectionUtil.readField(SPropertyAccessor.class, ((SPropertyAccessor) _PFparameters.get(0)), "myProperty"));
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getIcon", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Property.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getIcon_36";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Property)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return MPSIcons.CellExplorer.CellProperty;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getIcon", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Constant.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getIcon_37";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Constant)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return MPSIcons.CellExplorer.CellConst;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getIcon", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Collection.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getIcon_38";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Collection)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return MPSIcons.CellExplorer.Cells;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getIcon", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Error.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getIcon_39";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Error)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return MPSIcons.CellExplorer.CellError;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getIcon", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getIcon_40";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return MPSIcons.CellExplorer.CellDefault;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
    myImplementations.put("de.q60.mps.explorer.impl.pf.PF_EditorCells.getIcon", new IFunctionImplementation() {
      private List<IParameterType> myParameterTypes = ListSequence.fromListAndArray(new ArrayList<IParameterType>(), new ParameterType_Classifier(EditorCell_Component.class));
      private List<String> contextIds = ListSequence.fromList(new ArrayList<String>());
      private List<String> groupIds = ListSequence.fromList(new ArrayList<String>());
      @Override
      public String getId() {
        return "de.q60.mps.explorer.impl.pf/PF_EditorCells/getIcon_41";
      }
      public boolean isApplicable(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        if (!(_PFparameters.get(0) == null || _PFparameters.get(0) instanceof EditorCell_Component)) {
          return false;
        }
        return true;
      }
      public Object execute(final IPFContext _PFcontext, final ParameterList _PFparameters) {
        return MPSIcons.CellExplorer.CellComponent;
      }
      @Override
      public Iterable<IParameterType> getParameterTypes() {
        return myParameterTypes;
      }
      @Override
      public Iterable<String> getContextIds() {
        return contextIds;
      }
      @Override
      public Iterable<String> getPriorityGroupIds() {
        return groupIds;
      }
    });
  }
  private static String check_sog9z1_a0a0a1a91(SProperty checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getName();
    }
    return null;
  }
  private static String check_sog9z1_a0a0a0a1a91(SAbstractConcept checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getName();
    }
    return null;
  }
  private static SAbstractConcept check_sog9z1_a0a0a0a0b0t(SProperty checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getOwner();
    }
    return null;
  }
}
