package de.itemis.mps.editor.pagination.runtime.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.part.ProjectPluginPart;
import jetbrains.mps.openapi.editor.extensions.EditorExtension;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.openapi.editor.EditorComponent;
import jetbrains.mps.smodel.language.LanguageRegistryListener;
import jetbrains.mps.smodel.language.LanguageRuntime;
import java.util.stream.StreamSupport;
import java.util.Objects;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.project.MPSProject;
import jetbrains.mps.openapi.editor.extensions.EditorExtensionRegistry;
import jetbrains.mps.smodel.language.LanguageRegistry;

public class PaginationPlugin_ProjectPluginPart extends ProjectPluginPart {
  private EditorExtension extension = new EditorExtension() {
    @Override
    public boolean isApplicable(@NotNull EditorComponent p1) {
      return true;
    }

    @Override
    public void install(@NotNull EditorComponent editorComponent) {
      PaginationListener.getOrCreateInstance(((jetbrains.mps.nodeEditor.EditorComponent) editorComponent)).install();
    }

    @Override
    public void uninstall(@NotNull EditorComponent editorComponent) {
      check_sc6i86_a0a4a0a0(PaginationListener.getInstance(((jetbrains.mps.nodeEditor.EditorComponent) editorComponent)));
    }
  };
  private LanguageRegistryListener unloadListener = new LanguageRegistryListener() {
    @Override
    public void afterLanguagesLoaded(Iterable<LanguageRuntime> p1) {
    }

    @Override
    public void beforeLanguagesUnloaded(Iterable<LanguageRuntime> runtimes) {
      if (StreamSupport.stream(runtimes.spliterator(), false).anyMatch((LanguageRuntime runtime) -> Objects.equals(runtime.getIdentity(), MetaAdapterFactory.getLanguage(0x232ef711abb34b52L, 0xa3f2e7987a748232L, "de.itemis.mps.editor.pagination")))) {
        PaginationListener.uninstallAll();
      }
    }
  };
  public PaginationPlugin_ProjectPluginPart() {
  }
  @Override
  public void init(MPSProject project) {
    EditorExtension extension = PaginationPlugin_ProjectPluginPart.this.extension;
    check_sc6i86_a1a0(project.getComponent(EditorExtensionRegistry.class), extension);
    LanguageRegistry.getInstance(project.getRepository()).addRegistryListener(PaginationPlugin_ProjectPluginPart.this.unloadListener);
  }
  @Override
  public void dispose(MPSProject project) {
    EditorExtension extension = PaginationPlugin_ProjectPluginPart.this.extension;
    check_sc6i86_a1a0_0(project.getComponent(EditorExtensionRegistry.class), extension);
    LanguageRegistry.getInstance(project.getRepository()).removeRegistryListener(PaginationPlugin_ProjectPluginPart.this.unloadListener);
  }
  private static void check_sc6i86_a0a4a0a0(PaginationListener checkedDotOperand) {
    if (null != checkedDotOperand) {
      checkedDotOperand.uninstall();
    }

  }
  private static void check_sc6i86_a1a0(EditorExtensionRegistry checkedDotOperand, EditorExtension extension) {
    if (null != checkedDotOperand) {
      checkedDotOperand.registerExtension(extension);
    }

  }
  private static void check_sc6i86_a1a0_0(EditorExtensionRegistry checkedDotOperand, EditorExtension extension) {
    if (null != checkedDotOperand) {
      checkedDotOperand.unregisterExtension(extension);
    }

  }
}
