package de.q60.mps.shadowmodels.transformation.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import java.util.Iterator;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_ForkCall_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_ForkCall_InferenceRule() {
  }
  public void applyRule(final SNode n, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    int expectedNumParameters = ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(n, LINKS.decl$gcXQ), LINKS.parameters$Qv6r)).count();
    if (ListSequence.fromList(SLinkOperations.getChildren(n, LINKS.parameterValues$geAX)).count() != expectedNumParameters) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(n, expectedNumParameters + " parameters expected", "r:fd3ba2d5-05a9-4b3b-93ad-a566c0e12538(de.q60.mps.shadowmodels.transformation.typesystem)", "4453020072217881190", null, errorTarget);
      }
    }
    {
      Iterator<SNode> decl_it = ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(n, LINKS.decl$gcXQ), LINKS.parameters$Qv6r)).iterator();
      Iterator<SNode> val_it = ListSequence.fromList(SLinkOperations.getChildren(n, LINKS.parameterValues$geAX)).iterator();
      SNode decl_var;
      SNode val_var;
      while (decl_it.hasNext() && val_it.hasNext()) {
        decl_var = decl_it.next();
        val_var = val_it.next();
        {
          SNode _nodeToCheck_1029348928467 = val_var;
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:fd3ba2d5-05a9-4b3b-93ad-a566c0e12538(de.q60.mps.shadowmodels.transformation.typesystem)", "4453020072217881209", 0, null);
          typeCheckingContext.createLessThanInequality((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:fd3ba2d5-05a9-4b3b-93ad-a566c0e12538(de.q60.mps.shadowmodels.transformation.typesystem)", "4453020072217881214", true), (SNode) typeCheckingContext.typeOf(decl_var, "r:fd3ba2d5-05a9-4b3b-93ad-a566c0e12538(de.q60.mps.shadowmodels.transformation.typesystem)", "4453020072217881211", true), false, true, _info_12389875345);
        }
      }
    }
    {
      SNode _nodeToCheck_1029348928467 = n;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:fd3ba2d5-05a9-4b3b-93ad-a566c0e12538(de.q60.mps.shadowmodels.transformation.typesystem)", "3824754023342694509", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:fd3ba2d5-05a9-4b3b-93ad-a566c0e12538(de.q60.mps.shadowmodels.transformation.typesystem)", "3824754023342694042", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(n, LINKS.decl$gcXQ), "r:fd3ba2d5-05a9-4b3b-93ad-a566c0e12538(de.q60.mps.shadowmodels.transformation.typesystem)", "3824754023342694525", true), _info_12389875345);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.ForkCall$g;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink decl$gcXQ = MetaAdapterFactory.getReferenceLink(0x94b64715a2634c36L, 0xa1388da14705ffa7L, 0x3514418512965e5cL, 0x3dcc4e299c7f8528L, "decl");
    /*package*/ static final SContainmentLink parameters$Qv6r = MetaAdapterFactory.getContainmentLink(0x94b64715a2634c36L, 0xa1388da14705ffa7L, 0x6589b7fbb0ed2719L, 0x3dcc4e299c66d7dbL, "parameters");
    /*package*/ static final SContainmentLink parameterValues$geAX = MetaAdapterFactory.getContainmentLink(0x94b64715a2634c36L, 0xa1388da14705ffa7L, 0x3514418512965e5cL, 0x3dcc4e299c7f852fL, "parameterValues");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ForkCall$g = MetaAdapterFactory.getConcept(0x94b64715a2634c36L, 0xa1388da14705ffa7L, 0x3514418512965e5cL, "de.q60.mps.shadowmodels.transformation.structure.ForkCall");
  }
}
