package de.slisson.mps.richtext.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import jetbrains.mps.ide.editor.EditorActionAccess;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import de.slisson.mps.richtext.runtime.selection.RichtextHelper;
import jetbrains.mps.ide.editor.MPSEditorDataKeys;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.nodeEditor.EditorComponent;
import org.jetbrains.mps.openapi.model.SNode;
import de.slisson.mps.editor.multiline.cells.EditorCell_Multiline;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import de.slisson.mps.editor.multiline.cells.EditorCell_Word;
import de.slisson.mps.richtext.runtime.selection.RichtextSelection;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class RichtextSelectionRootHome_Action extends BaseAction {
  private static final Icon ICON = null;

  public RichtextSelectionRootHome_Action() {
    super("Select Richtext Root Home", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setActionAccess(EditorActionAccess.UNDO_EDITOR);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  public boolean isApplicable(AnActionEvent event, final Map<String, Object> _params) {
    return (new RichtextHelper(event.getData(MPSEditorDataKeys.EDITOR_COMPONENT)).getTextNode() != null);
  }
  @Override
  public void doUpdate(@NotNull AnActionEvent event, final Map<String, Object> _params) {
    this.setEnabledState(event.getPresentation(), this.isApplicable(event, _params));
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      EditorComponent editorComponent = event.getData(MPSEditorDataKeys.EDITOR_COMPONENT);
      if (editorComponent != null && editorComponent.isInvalid()) {
        editorComponent = null;
      }
      if (editorComponent == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    RichtextHelper helper = new RichtextHelper(event.getData(MPSEditorDataKeys.EDITOR_COMPONENT));
    helper.getTextNode();
    SNode textNode = helper.getTextNode();
    EditorCell_Multiline multilineCell = (EditorCell_Multiline) event.getData(MPSEditorDataKeys.EDITOR_COMPONENT).findNodeCell(ListSequence.fromList(SLinkOperations.getChildren(textNode, LINKS.words$C8QZ)).last());
    EditorCell_Word firstCell = multilineCell.firstCell();
    RichtextSelection newSelection = RichtextSelection.create(helper.getFirstSelectedCell(), helper.getCaretPositionOfFirstSelectedCell(), firstCell, 0);
    event.getData(MPSEditorDataKeys.EDITOR_COMPONENT).getSelectionManager().pushSelection(newSelection);
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink words$C8QZ = MetaAdapterFactory.getContainmentLink(0x92d2ea165a424fdfL, 0xa676c7604efe3504L, 0x237c8da86a9e4e61L, 0x237c8da86a9e7aeeL, "words");
  }
}
