package de.slisson.mps.hacks.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Set;
import de.slisson.mps.hacks.editor.editorregistry.ConceptEditorRegistry;
import java.util.Collections;

public class ConceptEditorUtil {

  public static ConceptEditor getApplicableEditor(SAbstractConcept concept, Set<String> hints) {
    return new ConceptEditorRegistry(hints).getEditor(concept);
  }

  public static ConceptEditor getApplicableEditor(SAbstractConcept concept) {
    return getApplicableEditor(concept, Collections.<String>emptySet());
  }

}
