package de.itemis.mps.editor.math.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.SNodePointer;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class MathSymbolReferenceExpression_Constraints extends BaseConstraintsDescriptor {
  public MathSymbolReferenceExpression_Constraints() {
    super(CONCEPTS.MathSymbolReferenceExpression$Kf);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.decl$mxbT, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return ReferenceScopeProvider.fromHierarchy(CONCEPTS.MathSymbolDecl$$W, new SNodePointer("r:395eb30d-fc47-48cb-afa4-88e98c1b6fbb(de.itemis.mps.editor.math.constraints)", "981761841405838611"));
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept MathSymbolReferenceExpression$Kf = MetaAdapterFactory.getConcept(0x766348f76a674b85L, 0x9323384840132299L, 0x7e92b88d18302c6aL, "de.itemis.mps.editor.math.structure.MathSymbolReferenceExpression");
    /*package*/ static final SConcept MathSymbolDecl$$W = MetaAdapterFactory.getConcept(0x766348f76a674b85L, 0x9323384840132299L, 0x7e92b88d18268eafL, "de.itemis.mps.editor.math.structure.MathSymbolDecl");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink decl$mxbT = MetaAdapterFactory.getReferenceLink(0x766348f76a674b85L, 0x9323384840132299L, 0x7e92b88d18302c6aL, 0x7e92b88d1832b23aL, "decl");
  }
}
