package test.de.q60.mps.shadowmodels.examples;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheBuilder;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;

@MPSLaunch
public class Typesystem_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCacheBuilder(Typesystem_Test.class).projectPath(null).modelRef("r:d779ef4d-b8f4-4bf2-9b31-f1c1d22129f6(test.de.q60.mps.shadowmodels.examples@tests)").reopenProject(null).build());

  public Typesystem_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_repositoryMode() throws Throwable {
    new TestBody(this).test_repositoryMode();
  }
  @Test
  public void test_nonRepositoryMode() throws Throwable {
    new TestBody(this).test_nonRepositoryMode();
  }

  /*package*/ static class TestBody extends BaseTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    protected void initTestNodes() {
      prepareTestNodes("8286906820979266302", "8286906820979266328");
    }

    public void test_repositoryMode() throws Exception {
      initTestNodes();
      runWithinCommand(() -> TransformationTestUtil.runTest(getAnnotatedNode("input"), getAnnotatedNode("expectedOutput"), new SNodePointer("r:c375a18d-71ae-4a50-a794-bc6969ddf849(de.q60.mps.shadowmodels.examples.blext.transformations)", "6198477943071245066"), ListSequence.fromListAndArray(new ArrayList<SModuleReference>(), PersistenceFacade.getInstance().createModuleReference("bbb5f4e2-794a-4b91-bd27-caf7d437ac9e(de.q60.mps.shadowmodels.examples.blext)")), true));
    }
    public void test_nonRepositoryMode() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        TransformationTestUtil.runTest(getAnnotatedNode("input"), getAnnotatedNode("expectedOutput"), new SNodePointer("r:c375a18d-71ae-4a50-a794-bc6969ddf849(de.q60.mps.shadowmodels.examples.blext.transformations)", "6198477943071245066"), ListSequence.fromListAndArray(new ArrayList<SModuleReference>(), PersistenceFacade.getInstance().createModuleReference("bbb5f4e2-794a-4b91-bd27-caf7d437ac9e(de.q60.mps.shadowmodels.examples.blext)")), false);

      });
    }

  }
}
