package de.itemis.model.merge.test.test1;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.ClassRule;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.test.runtime.CheckExpectedMessageRunnable;
import jetbrains.mps.errors.MessageStatus;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.project.ProjectBase;
import jetbrains.mps.lang.test.runtime.CheckErrorMessagesRunnable;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

@MPSLaunch
public class IdFunctionTests_Test extends BaseTransformationTest {
  @ClassRule
  public static final TestParametersCache ourParamCache = new TestParametersCache(IdFunctionTests_Test.class, "${extensions.home}/code", "r:d4903c79-201b-45bc-809e-5c65a3994bca(de.itemis.model.merge.test.test1@tests)", false);

  public IdFunctionTests_Test() {
    super(ourParamCache);
  }

  @Test
  public void test_NodeConceptIsMissingIdFunctionCheck5949612680091520140() throws Throwable {
    new TestBody(this).test_NodeConceptIsMissingIdFunctionCheck5949612680091520140();
  }
  @Test
  public void test_ErrorMessagesCheck5949612680091647331() throws Throwable {
    new TestBody(this).test_ErrorMessagesCheck5949612680091647331();
  }
  @Test
  public void test_NodeIsAlreadyDefinedMultipleCheck5949612680091695945() throws Throwable {
    new TestBody(this).test_NodeIsAlreadyDefinedMultipleCheck5949612680091695945();
  }

  /*package*/ static class TestBody extends BaseTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    public void test_NodeConceptIsMissingIdFunctionCheck5949612680091520140() throws Exception {

      runWithinCommand(() -> {
        SNode nodeToCheck = getRealNodeById("5949612680091520127");
        SNode operation = getRealNodeById("5949612680091520140");
        new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(nodeToCheck, MessageStatus.WARNING, new SNodePointer("r:02b6652e-c87d-4bb2-bfc0-4b5c0d5b9442(de.itemis.model.merge.typesystem)", "6922793481539920664"), "", myProject.getRepository(), ((ProjectBase) myProject).getPlatform()).run();
      });
    }
    public void test_ErrorMessagesCheck5949612680091647331() throws Exception {

      runWithinCommand(() -> {
        SNode nodeToCheck = getRealNodeById("5949612680091038434");
        SNode operation = getRealNodeById("5949612680091647331");
        new CheckErrorMessagesRunnable(nodeToCheck, false, false, ((ProjectBase) myProject).getPlatform()).includeSelf(true).exclude(ListSequence.fromList(new ArrayList<CheckExpectedMessageRunnable>())).run();
      });
    }
    public void test_NodeIsAlreadyDefinedMultipleCheck5949612680091695945() throws Exception {

      runWithinCommand(() -> {
        SNode nodeToCheck = getRealNodeById("5949612680091694265");
        SNode operation = getRealNodeById("5949612680091695945");
        new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(nodeToCheck, MessageStatus.ERROR, new SNodePointer("r:02b6652e-c87d-4bb2-bfc0-4b5c0d5b9442(de.itemis.model.merge.typesystem)", "9112015721049551246"), "", myProject.getRepository(), ((ProjectBase) myProject).getPlatform()).run();
      });
    }

  }
}
