package de.itemis.model.merge.test.integration.plugin;

/*Generated by MPS */

import de.itemis.model.merge.runtime.runtime.ConceptMergeSpec;
import java.util.Arrays;
import de.itemis.model.merge.runtime.runtime.PropertyMerger;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import de.itemis.model.merge.runtime.runtime.ConceptChildMerger;
import de.itemis.model.merge.runtime.runtime.ConceptRefMerger;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Annotatable_mergepolicy_Annotatable_v26e6n_c extends ConceptMergeSpec {

  public Annotatable_mergepolicy_Annotatable_v26e6n_c() {
    super(CONCEPTS.Annotatable$gt, Arrays.<PropertyMerger>asList(new PropertyMerger() {
      @Override
      public SProperty property() {
        return PROPS.value$Iwma;
      }

      @Override
      public Object merge(SNode left, SNode right) {
        return SPropertyOperations.getInteger(left, PROPS.value$Iwma) + SPropertyOperations.getInteger(right, PROPS.value$Iwma);
      }
    }), Arrays.<ConceptChildMerger>asList(), Arrays.<ConceptRefMerger>asList());
  }


  private String innerId(SNode instance) {
    return SPropertyOperations.getInteger(instance, PROPS.value$Iwma) + "";
  }

  @Override
  public String id(SNode node) {
    return this.innerId(node);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Annotatable$gt = MetaAdapterFactory.getConcept(0xc527d4ce1a24433bL, 0xb1ec929a89de103aL, 0xf045b38d3fc98b1L, "de.itemis.model.merge.simple.demo.annotated.structure.Annotatable");
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$Iwma = MetaAdapterFactory.getProperty(0xc527d4ce1a24433bL, 0xb1ec929a89de103aL, 0xf045b38d3fc98b1L, 0xf045b38d3fc98b4L, "value");
  }
}
