package de.slisson.mps.reflection.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_ReflectionFieldAccess;
  private ConceptPresentation props_ReflectionMethodCall;
  private ConceptPresentation props_ReflectionStaticFieldReference;
  private ConceptPresentation props_ReflectionStaticMethodCall;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.ReflectionFieldAccess:
        if (props_ReflectionFieldAccess == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.deprecated(true);
          cpb.presentationByReference(0x654422bfe75f44dcL, 0x936d188890a746ceL, 0x7598281400c6a454L, 0x116b484a653L, "fieldDeclaration", "", "");
          props_ReflectionFieldAccess = cpb.create();
        }
        return props_ReflectionFieldAccess;
      case LanguageConceptSwitch.ReflectionMethodCall:
        if (props_ReflectionMethodCall == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.deprecated(true);
          cpb.presentationByReference(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration", "", "");
          props_ReflectionMethodCall = cpb.create();
        }
        return props_ReflectionMethodCall;
      case LanguageConceptSwitch.ReflectionStaticFieldReference:
        if (props_ReflectionStaticFieldReference == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.deprecated(true);
          cpb.rawPresentation("ReflectionStaticFieldReference");
          props_ReflectionStaticFieldReference = cpb.create();
        }
        return props_ReflectionStaticFieldReference;
      case LanguageConceptSwitch.ReflectionStaticMethodCall:
        if (props_ReflectionStaticMethodCall == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.deprecated(true);
          cpb.rawPresentation("ReflectionStaticMethodCall");
          props_ReflectionStaticMethodCall = cpb.create();
        }
        return props_ReflectionStaticMethodCall;
    }
    return null;
  }
}
