package de.itemis.mps.editor.diagram.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PolyominoHighLevelSortingCriterion extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PolyominoHighLevelSortingCriterion() {
    super(0xfa13cc63c4764d46L, 0x9c96d53670abe7bcL, 0x6a0cd762a3d64cbL, "PolyominoHighLevelSortingCriterion", "r:24bac084-437d-402d-b9a3-49599b18a0d1(de.itemis.mps.editor.diagram.structure)/477607467899774155");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_NUM_OF_EXTERNAL_SIDES_THAN_NUM_OF_EXTENSIONS_LAST_0 = new EnumerationDescriptor.MemberDescriptor("NUM_OF_EXTERNAL_SIDES_THAN_NUM_OF_EXTENSIONS_LAST", "NUM_OF_EXTERNAL_SIDES_THAN_NUM_OF_EXTENSIONS_LAST", 0x6a0cd762a3d64ccL, "r:24bac084-437d-402d-b9a3-49599b18a0d1(de.itemis.mps.editor.diagram.structure)/477607467899774156");
  private final EnumerationDescriptor.MemberDescriptor myMember_CORNER_CASES_THAN_SINGLE_SIDE_LAST_0 = new EnumerationDescriptor.MemberDescriptor("CORNER_CASES_THAN_SINGLE_SIDE_LAST", "CORNER_CASES_THAN_SINGLE_SIDE_LAST", 0x6a0cd762a3d653bL, "r:24bac084-437d-402d-b9a3-49599b18a0d1(de.itemis.mps.editor.diagram.structure)/477607467899774267");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xfa13cc63c4764d46L, 0x9c96d53670abe7bcL, 0x6a0cd762a3d64cbL, 0x6a0cd762a3d64ccL, 0x6a0cd762a3d653bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_NUM_OF_EXTERNAL_SIDES_THAN_NUM_OF_EXTENSIONS_LAST_0, myMember_CORNER_CASES_THAN_SINGLE_SIDE_LAST_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_NUM_OF_EXTERNAL_SIDES_THAN_NUM_OF_EXTENSIONS_LAST_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "NUM_OF_EXTERNAL_SIDES_THAN_NUM_OF_EXTENSIONS_LAST":
        return myMember_NUM_OF_EXTERNAL_SIDES_THAN_NUM_OF_EXTENSIONS_LAST_0;
      case "CORNER_CASES_THAN_SINGLE_SIDE_LAST":
        return myMember_CORNER_CASES_THAN_SINGLE_SIDE_LAST_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
