package com.dslfoundry.langvis.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class Toolbar_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "com.dslfoundry.langvis.plugin.plugin.Toolbar_ActionGroup";

  public Toolbar_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("Toolbar", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    updateInBackground(true);
    Toolbar_ActionGroup.this.addAction("com.dslfoundry.langvis.plugin.plugin.Reload_Action");
    Toolbar_ActionGroup.this.addSeparator();
    Toolbar_ActionGroup.this.addAction("com.dslfoundry.langvis.plugin.plugin.ZoomIn_Action");
    Toolbar_ActionGroup.this.addAction("com.dslfoundry.langvis.plugin.plugin.ZoomOut_Action");
    Toolbar_ActionGroup.this.addSeparator();
    Toolbar_ActionGroup.this.addAction("com.dslfoundry.langvis.plugin.plugin.ZoomOneToOne_Action");
    Toolbar_ActionGroup.this.addAction("com.dslfoundry.langvis.plugin.plugin.ZoomMax_Action");
  }
}
