package de.itemis.mps.compare.pattern.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseConstraintsAspectDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class ConstraintsAspectDescriptor extends BaseConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }

  @Override
  @Nullable
  public ConstraintsDescriptor getConstraints(@NotNull SAbstractConcept concept, @NotNull ConstraintsDescriptorInitContext context) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return new AncestorMember_Constraints(context);
      case 1:
        return new GetConceptOperation_Constraints(context);
      case 2:
        return new IInitPart_Constraints(context);
      case 3:
        return new LinkMember_Constraints(context);
      case 4:
        return new MemberAnnotation_Constraints(context);
      case 5:
        return new NotNullLiteral_Constraints(context);
      case 6:
        return new NullLiteral_Constraints(context);
      case 7:
        return new ParentMember_Constraints(context);
      case 8:
        return new Pattern_Constraints(context);
      case 9:
        return new PatternBuilderExpression_Constraints(context);
      case 10:
        return new PatternBuilderList_Constraints(context);
      case 11:
        return new PatternBuilderNode_Constraints(context);
      case 12:
        return new PatternRefExpression_Constraints(context);
      case 13:
        return new PropertyMember_Constraints(context);
      case 14:
        return new TypeMember_Constraints(context);
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0b118bL), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x369e63b317eee47dL), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0b0bf4L), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0efaf2L), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x93c76ef17957ee3L), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x45a266271d194fecL), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x45a266271d194fe8L), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0b119eL), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0b4127L), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x143963f77e303efL), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x143963f77e34f7eL), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0fa22eL), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x143963f77e37fc0L), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0efaf7L), MetaIdFactory.conceptId(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0b119cL)).seal();
}
