package de.itemis.mps.compare.pattern.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintFunction;
import jetbrains.mps.smodel.runtime.ConstraintContext_CanBeParent;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.smodel.runtime.ConstraintContext_CanBeAncestor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TypeMember_Constraints extends BaseConstraintsDescriptor {
  public TypeMember_Constraints() {
    super(CONCEPTS.TypeMember$jE);
  }

  @Override
  protected ConstraintFunction<ConstraintContext_CanBeParent, Boolean> calculateCanBeParentConstraint() {
    return new ConstraintFunction<ConstraintContext_CanBeParent, Boolean>() {
      @NotNull
      public Boolean invoke(@NotNull ConstraintContext_CanBeParent context, @Nullable CheckingNodeContext checkingNodeContext) {
        boolean result = staticCanBeAParent(context.getNode(), context.getChildNode(), context.getChildConcept(), context.getLink());

        if (!(result) && checkingNodeContext != null) {
          checkingNodeContext.setBreakingNode(canBeParentBreakingPoint);
        }

        return result;
      }
    };
  }
  @Override
  protected ConstraintFunction<ConstraintContext_CanBeAncestor, Boolean> calculateCanBeAncestorConstraint() {
    return new ConstraintFunction<ConstraintContext_CanBeAncestor, Boolean>() {
      @NotNull
      public Boolean invoke(@NotNull ConstraintContext_CanBeAncestor context, @Nullable CheckingNodeContext checkingNodeContext) {
        boolean result = staticCanBeAnAncestor(context.getNode(), context.getChildNode(), context.getChildConcept(), context.getParentNode(), context.getLink());

        if (!(result) && checkingNodeContext != null) {
          checkingNodeContext.setBreakingNode(canBeAncestorBreakingPoint);
        }

        return result;
      }
    };
  }
  private static boolean staticCanBeAParent(SNode node, SNode childNode, SAbstractConcept childConcept, SContainmentLink link) {
    return SConceptOperations.isExactly(SNodeOperations.asSConcept(childConcept), CONCEPTS.PatternRefExpression$7) || SConceptOperations.isExactly(SNodeOperations.asSConcept(childConcept), CONCEPTS.PatternBuilderNode$5G) || SConceptOperations.isExactly(SNodeOperations.asSConcept(childConcept), CONCEPTS.NullLiteral$vO) || SConceptOperations.isExactly(SNodeOperations.asSConcept(childConcept), CONCEPTS.NotNullLiteral$xK) || SConceptOperations.isExactly(SNodeOperations.asSConcept(childConcept), CONCEPTS.MemberAnnotation$ww);
  }
  private static boolean staticCanBeAnAncestor(SNode node, SNode childNode, SAbstractConcept childConcept, SNode parentNode, SContainmentLink link) {
    return !(SConceptOperations.isExactly(SNodeOperations.asSConcept(childConcept), CONCEPTS.AncestorMember$R5)) && !(SConceptOperations.isExactly(SNodeOperations.asSConcept(childConcept), CONCEPTS.ParentMember$kC)) && !(SConceptOperations.isExactly(SNodeOperations.asSConcept(childConcept), CONCEPTS.TypeMember$jE));
  }
  private static final SNodePointer canBeParentBreakingPoint = new SNodePointer("r:4c1042ac-caa8-4069-87b6-b203297a333f(de.itemis.mps.compare.pattern.constraints)", "6768392667014055833");
  private static final SNodePointer canBeAncestorBreakingPoint = new SNodePointer("r:4c1042ac-caa8-4069-87b6-b203297a333f(de.itemis.mps.compare.pattern.constraints)", "6768392667014055810");

  private static final class CONCEPTS {
    /*package*/ static final SConcept TypeMember$jE = MetaAdapterFactory.getConcept(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0b119cL, "de.itemis.mps.compare.pattern.structure.TypeMember");
    /*package*/ static final SConcept PatternRefExpression$7 = MetaAdapterFactory.getConcept(0x17566462d8374552L, 0x874c64e45c10778aL, 0x143963f77e37fc0L, "de.itemis.mps.compare.pattern.structure.PatternRefExpression");
    /*package*/ static final SConcept PatternBuilderNode$5G = MetaAdapterFactory.getConcept(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0fa22eL, "de.itemis.mps.compare.pattern.structure.PatternBuilderNode");
    /*package*/ static final SConcept NullLiteral$vO = MetaAdapterFactory.getConcept(0x17566462d8374552L, 0x874c64e45c10778aL, 0x45a266271d194fe8L, "de.itemis.mps.compare.pattern.structure.NullLiteral");
    /*package*/ static final SConcept NotNullLiteral$xK = MetaAdapterFactory.getConcept(0x17566462d8374552L, 0x874c64e45c10778aL, 0x45a266271d194fecL, "de.itemis.mps.compare.pattern.structure.NotNullLiteral");
    /*package*/ static final SConcept MemberAnnotation$ww = MetaAdapterFactory.getConcept(0x17566462d8374552L, 0x874c64e45c10778aL, 0x93c76ef17957ee3L, "de.itemis.mps.compare.pattern.structure.MemberAnnotation");
    /*package*/ static final SConcept AncestorMember$R5 = MetaAdapterFactory.getConcept(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0b118bL, "de.itemis.mps.compare.pattern.structure.AncestorMember");
    /*package*/ static final SConcept ParentMember$kC = MetaAdapterFactory.getConcept(0x17566462d8374552L, 0x874c64e45c10778aL, 0x316a248a9a0b119eL, "de.itemis.mps.compare.pattern.structure.ParentMember");
  }
}
