package de.slisson.mps.javadoc.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import de.slisson.mps.javadoc.behavior.HtmlTag__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class HtmlTag_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<");
    tgs.append(HtmlTag__BehaviorDescriptor.getTagname_id2YgkUiABxIb.invoke(SNodeOperations.asSConcept(SNodeOperations.getConcept(ctx.getPrimaryInput()))));
    tgs.append(">");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.text$9d0D));
    tgs.append("</");
    tgs.append(HtmlTag__BehaviorDescriptor.getTagname_id2YgkUiABxIb.invoke(SNodeOperations.asSConcept(SNodeOperations.getConcept(ctx.getPrimaryInput()))));
    tgs.append(">");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink text$9d0D = MetaAdapterFactory.getContainmentLink(0x4e0df6bde2654d63L, 0x9ca0ca97e44cf841L, 0x4ac464ef5c6fd770L, 0x4ac464ef5c6fd772L, "text");
  }
}
