package de.itemis.mps.editor.pagination.runtime.ui;

/*Generated by MPS */

import javax.swing.JPanel;
import de.itemis.mps.editor.pagination.runtime.pages.PagesUserObject;
import jetbrains.mps.openapi.editor.EditorContext;
import javax.swing.JButton;
import jetbrains.mps.nodeEditor.EditorSettings;
import com.intellij.icons.AllIcons;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JCheckBox;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import java.awt.event.FocusListener;
import java.awt.event.FocusEvent;

public class PaginationSearchPanel extends JPanel {

  private PagesUserObject myUserObject;
  private EditorContext myContext;

  private JButton previousBtn;
  private JButton nextBtn;
  private JButton clearResultsBtn;
  private final PaginationSearchField searchField;
  private SearchOptionState searchOptionState = new SearchOptionState();

  public class SearchOptionState {
    private boolean matchCase = false;
    private boolean matchRegex = false;
    private boolean matchWords = false;

    public void setMatchCase(boolean flag) {
      matchCase = flag;
    }

    public boolean isMatchCase() {
      return matchCase;
    }

    public void setMatchRegex(boolean flag) {
      matchRegex = flag;
    }

    public boolean isMatchRegex() {
      return matchRegex;
    }

    public void setMatchWords(boolean flag) {
      matchWords = flag;
    }

    public boolean isMatchWords() {
      return matchWords;
    }
  }

  public static int iconButtonWidth = 30;

  public PaginationSearchPanel(PagesUserObject userObject, final EditorContext context) {
    myUserObject = userObject;
    myContext = context;

    setOpaque(false);
    putClientProperty("ActionToolbar.smallVariant", true);
    setFont(EditorSettings.getInstance().getDefaultEditorFont());

    searchField = new PaginationSearchField(myUserObject, this, context);
    add(searchField);

    previousBtn = new JButton(AllIcons.Chooser.Left);
    previousBtn.setToolTipText("Previous result");
    previousBtn.setPreferredSize(new Dimension(iconButtonWidth, previousBtn.getPreferredSize().height));
    previousBtn.setOpaque(false);
    previousBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent event) {
        context.getRepository().getModelAccess().runReadAction(() -> PaginationSearchResultManager.getInstance().goToNextResult(myUserObject, false, context));
      }
    });
    add(previousBtn);

    nextBtn = new JButton(AllIcons.Chooser.Right);
    nextBtn.setToolTipText("Next result");
    nextBtn.setPreferredSize(new Dimension(iconButtonWidth, nextBtn.getPreferredSize().height));

    nextBtn.setOpaque(false);
    nextBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent event) {
        context.getRepository().getModelAccess().runReadAction(() -> PaginationSearchResultManager.getInstance().goToNextResult(myUserObject, true, context));
      }
    });
    add(nextBtn);

    clearResultsBtn = new JButton(AllIcons.Vcs.Remove);
    clearResultsBtn.setToolTipText("Clear results");
    clearResultsBtn.setPreferredSize(new Dimension(iconButtonWidth, clearResultsBtn.getPreferredSize().height));

    clearResultsBtn.setOpaque(false);
    clearResultsBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent event) {
        context.getRepository().getModelAccess().runReadAction(() -> PaginationSearchResultManager.getInstance().clearResults(myUserObject, context));
        updateButtons();
      }
    });
    add(clearResultsBtn);

    JCheckBox ignoreCaseCheckbox = new JCheckBox("Match Case");
    ignoreCaseCheckbox.setToolTipText("Search for exact capitalization.");
    ignoreCaseCheckbox.setOpaque(false);
    ignoreCaseCheckbox.addItemListener(new ItemListener() {
      @Override
      public void itemStateChanged(ItemEvent event) {
        searchOptionState.setMatchCase(event.getStateChange() == ItemEvent.SELECTED);
      }
    });
    add(ignoreCaseCheckbox);

    JCheckBox regexCheckbox = new JCheckBox("Regex");
    regexCheckbox.setToolTipText("Use a regular expression for searching.");
    regexCheckbox.setOpaque(false);
    regexCheckbox.addItemListener(new ItemListener() {
      @Override
      public void itemStateChanged(ItemEvent event) {
        searchOptionState.setMatchRegex(event.getStateChange() == ItemEvent.SELECTED);
      }
    });
    add(regexCheckbox);

    JCheckBox wordsCheckbox = new JCheckBox("Words");
    wordsCheckbox.setToolTipText("Only match whole words.");
    wordsCheckbox.setOpaque(false);
    wordsCheckbox.addItemListener(new ItemListener() {
      @Override
      public void itemStateChanged(ItemEvent event) {
        searchOptionState.setMatchCase(event.getStateChange() == ItemEvent.SELECTED);
      }
    });
    add(wordsCheckbox);

    updateButtons();

    // restore selection
    SNode currentlySelectedNode = PaginationSearchResultManager.getInstance().getCurrentlySelectedNode(myUserObject);
    if ((currentlySelectedNode != null)) {
      context.select(currentlySelectedNode);
    }
  }

  public void syncWithEditorCell(final EditorCell cell) {
    // focus the editor cell to avoid the insert action
    this.searchField.getTextEditor().addFocusListener(new FocusListener() {
      @Override
      public void focusGained(FocusEvent p1) {
        myContext.getSelectionManager().setSelection(cell);
      }

      @Override
      public void focusLost(FocusEvent p1) {
      }
    });
  }

  public void updateButtons() {
    JButton[] buttons = new JButton[]{previousBtn, nextBtn, clearResultsBtn};

    for (final JButton button : buttons) {
      myContext.getRepository().getModelAccess().runReadAction(() -> {
        if (PaginationSearchResultManager.getInstance().getCurrentlySelectedNode(myUserObject) != null) {
          button.setVisible(true);
        } else {
          button.setVisible(false);
        }
      });
    }
  }

  public SearchOptionState getSearchOptionState() {
    return searchOptionState;
  }

  @Override
  public String toString() {
    return "[search panel]";
  }
}
