package com.mbeddr.mpsutil.editor.querylist.demolang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new RootConcept_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new RootDynamicContent_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new RootWithChildren_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new StatementWrapper_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x9b71d0dbbcaf4144L, 0xbb2e1ddef2b249b9L, 0x5614574a4a389a7dL), MetaIdFactory.conceptId(0x9b71d0dbbcaf4144L, 0xbb2e1ddef2b249b9L, 0x57cc27d84aa15930L), MetaIdFactory.conceptId(0x9b71d0dbbcaf4144L, 0xbb2e1ddef2b249b9L, 0x1b1987b5a639ba5dL), MetaIdFactory.conceptId(0x9b71d0dbbcaf4144L, 0xbb2e1ddef2b249b9L, 0x575be1494452189L)).seal();
}
