package de.itemis.mps.editor.diagram.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EdgeRoutingMode extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EdgeRoutingMode() {
    super(0xfa13cc63c4764d46L, 0x9c96d53670abe7bcL, 0x6a0cd762ababb4eL, "EdgeRoutingMode", "r:24bac084-437d-402d-b9a3-49599b18a0d1(de.itemis.mps.editor.diagram.structure)/477607467907988302");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_NONE_0 = new EnumerationDescriptor.MemberDescriptor("NONE", "NONE", 0x6a0cd762ababb4fL, "r:24bac084-437d-402d-b9a3-49599b18a0d1(de.itemis.mps.editor.diagram.structure)/477607467907988303");
  private final EnumerationDescriptor.MemberDescriptor myMember_MIDDLE_TO_MIDDLE_0 = new EnumerationDescriptor.MemberDescriptor("MIDDLE_TO_MIDDLE", "MIDDLE_TO_MIDDLE", 0x6a0cd762ababb5cL, "r:24bac084-437d-402d-b9a3-49599b18a0d1(de.itemis.mps.editor.diagram.structure)/477607467907988316");
  private final EnumerationDescriptor.MemberDescriptor myMember_AVOID_OVERLAP_0 = new EnumerationDescriptor.MemberDescriptor("AVOID_OVERLAP", "AVOID_OVERLAP", 0x6a0cd762ababb60L, "r:24bac084-437d-402d-b9a3-49599b18a0d1(de.itemis.mps.editor.diagram.structure)/477607467907988320");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xfa13cc63c4764d46L, 0x9c96d53670abe7bcL, 0x6a0cd762ababb4eL, 0x6a0cd762ababb4fL, 0x6a0cd762ababb5cL, 0x6a0cd762ababb60L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_NONE_0, myMember_MIDDLE_TO_MIDDLE_0, myMember_AVOID_OVERLAP_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_AVOID_OVERLAP_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "NONE":
        return myMember_NONE_0;
      case "MIDDLE_TO_MIDDLE":
        return myMember_MIDDLE_TO_MIDDLE_0;
      case "AVOID_OVERLAP":
        return myMember_AVOID_OVERLAP_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
