package de.itemis.mps.editor.pagination.runtime.pages;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.Objects;

public class PagesUserObject {
  private final SNode nodeWithPagination;
  private final SContainmentLink linkToPaginate;
  private final int pageSize;

  public PagesUserObject(SNode nodeWithPagination, SContainmentLink linkToPaginate, int pageSize) {
    this.nodeWithPagination = nodeWithPagination;
    this.linkToPaginate = linkToPaginate;
    this.pageSize = pageSize;
  }

  public PagesUserObject(SNode nodeWithPagination, SNode childToPaginate, int pageSize) {
    this(nodeWithPagination, SNodeOperations.getContainingLink(childToPaginate), pageSize);
  }

  public SNode getNodeWithPagination() {
    return this.nodeWithPagination;
  }

  public SContainmentLink getLinkToPaginate() {
    return this.linkToPaginate;
  }

  public List<SNode> getAllChildren() {
    List<SNode> nodes = ListSequence.fromList(new ArrayList<SNode>());
    ListSequence.fromList(nodes).addSequence(Sequence.fromIterable(getNodeWithPagination().getChildren(getLinkToPaginate())));
    return nodes;
  }

  public int size() {
    return getPages().size();
  }

  public int getPageSize() {
    return this.pageSize;
  }

  public boolean contains(SNode n) {
    return getPages().contains(n);
  }

  public boolean hasNext() {
    return getPages().hasNext();
  }

  public void next() {
    setPages(getPages().next());
  }

  public boolean hasPrevious() {
    return getPages().hasPrevious();
  }

  public void previous() {
    setPages(getPages().previous());
  }

  public void goTo(int pageNumber) {
    setPages(getPages().getPagesWith(pageNumber));
  }

  public int getCurrentPage() {
    return getPages().getCurrentPage().getPageNumber().getValue();
  }

  public void setPages(Pages pages) {
    set(getNodeWithPagination(), getLinkToPaginate(), pages);
  }

  public Pages getPages() {
    return getOrCreate(getNodeWithPagination(), getLinkToPaginate(), getPageSize());
  }

  public static Pages get(SNode nodeWithPagination, SContainmentLink linkToPaginate) {
    return as_chn8bb_a0a0kb(nodeWithPagination.getUserObject(linkToPaginate), Pages.class);
  }

  public static Pages getOrCreate(SNode nodeWithPagination, final SContainmentLink linkToPaginate, int pageSize) {
    Pages pages = get(nodeWithPagination, linkToPaginate);
    if (pages == null || pages.getCurrentPage().getPageSize() != pageSize) {
      pages = new Pages(ListSequence.fromList(SNodeOperations.getChildren(nodeWithPagination)).where((c) -> Objects.equals(SNodeOperations.getContainingLink(c), linkToPaginate)), pageSize);
      set(nodeWithPagination, linkToPaginate, pages);
    }
    return pages;
  }

  public static void set(SNode nodeWithPagination, SContainmentLink linkToPaginate, Pages pages) {
    nodeWithPagination.putUserObject(linkToPaginate, pages);
  }
  private static <T> T as_chn8bb_a0a0kb(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
